export default {
  'insights.officialBadge': 'Official regional data & demographics • 2024–2025',
  'insights.regionalInsights': 'Regional Insights',
  'insights.heroDescription': "Explore comprehensive public demographic data, foreign resident communities, tourism seasonality curves, and municipal district profiles for Türkiye's premier Mediterranean coastline — verified against official TÜİK, Ministry, and Migration registries.",
  'insights.demographics': 'Demographics', 'insights.tourismTrends': 'Tourism Trends', 'insights.districtProfiles': '8 District Profiles', 'insights.officialSources': 'Official Sources',
  'insights.provinceGlance': 'Antalya Province at a Glance', 'insights.provinceIndicators': 'Key demographic and geographic indicators across 19 municipal districts', 'insights.updatedAdnks': 'Updated ADNKS 2024/2025',
  'insights.districtIntelligence': 'District Intelligence & Expat Profiles', 'insights.population': 'Population', 'insights.foreigners': 'Foreigners', 'insights.blueFlag': 'Blue Flag', 'insights.searchPlaceholder': 'Search district, vibe, beach...', 'insights.clearSearch': 'Clear search',
  'insights.openData': 'Open Data Governance & Attribution', 'insights.officialDataSources': 'Official Data Sources & Registry Citations', 'insights.officialPortal': 'Official Portal Registry', 'insights.methodology': 'Methodological Note & Data Integrity', 'insights.visit': 'Visit', 'insights.dataset': 'Dataset',
  'insights.tourismDynamics': 'Tourism Flow & Seasonality Dynamics', 'insights.estimatedArrivals': 'Estimated Arrivals:', 'insights.annualShare': 'Annual Volume Share:', 'insights.avgAir': 'Avg Air:', 'insights.avgSea': 'Avg Sea:', 'insights.inboundVisitors': 'Inbound Visitors:', 'insights.marketShare': 'Market Share:', 'insights.yoyGrowth': 'YoY Growth:', 'insights.season': 'Season',
  'planner.targetDay': 'Target day when adding activities:', 'planner.thinking': 'Gemini AI Concierge is thinking...', 'planner.send': 'Send',
  'settings.noBookings': 'No bookings or inquiries found', 'settings.stayPeriod': 'Stay Period', 'settings.partySize': 'Party Size', 'settings.totalPrice': 'Total Price', 'settings.noFavorites': 'No saved favorites yet', 'settings.noForum': 'No forum discussions yet', 'settings.noOrders': 'No orders placed yet', 'settings.recipient': 'Recipient:', 'settings.totalAmount': 'Total Amount:', 'settings.personalInfo': 'Personal Information', 'settings.choosePreset': 'Or choose a preset:', 'settings.socialPresence': 'Social & Digital Presence', 'settings.reset': 'Reset', 'settings.saving': 'Saving...', 'settings.saveChanges': 'Save Changes', 'settings.noSaved': 'No saved discussions yet', 'settings.saved': 'Saved', 'settings.changePassword': 'Change Password', 'settings.success': 'Success', 'settings.passwordError': 'Error Updating Password', 'settings.passwordChecklist': 'Password Checklist:', 'settings.updatingPassword': 'Updating Password...', 'settings.updatePassword': 'Update Password', 'settings.securityRecommendations': 'Security Recommendations', 'settings.uniquePassword': 'Use a unique password not shared with any other platforms.', 'settings.passwordMix': 'Include a mix of uppercase letters, numbers, and symbols.', 'settings.neverShare': 'Never share your login credentials with unverified contacts.', 'settings.recoverAccount': 'Need Help Recovering Your Account?'
};
