export interface ForumEvent {
  id: string;
  title: string;
  date: string;
  day: string;
  month: string;
  time: string;
  location: string;
  category: string;
  attendees: number;
  maxAttendees: number;
  host: string;
  hostAvatar: string;
  description: string;
  image: string;
  isFeatured: boolean;
  slug?: string;
  going_by_me?: boolean;
}

export const events: ForumEvent[] = [
  {
    id: "e1",
    title: "Digital Nomad Beach Meetup",
    date: "2026-06-10",
    day: "10",
    month: "JUN",
    time: "4:00 PM",
    location: "Cleopatra Beach, Alanya",
    category: "Digital Nomad Events",
    attendees: 45,
    maxAttendees: 60,
    host: "Elena Kowalski",
    hostAvatar: "/images/placeholder-business.svg",
    description: "Monthly beach coworking session followed by sunset drinks. Bring your laptop, sunscreen, and good vibes. We will have a shaded area reserved and strong WiFi provided by the beach cafe.",
    image: "/images/placeholder-business.svg",
    isFeatured: true,
  },
  {
    id: "e2",
    title: "Sunset Boat Tour & BBQ",
    date: "2026-06-15",
    day: "15",
    month: "JUN",
    time: "6:30 PM",
    location: "Alanya Harbor",
    category: "Beach Gatherings",
    attendees: 32,
    maxAttendees: 40,
    host: "Mark Stevenson",
    hostAvatar: "/images/placeholder-business.svg",
    description: "Join us for a private boat cruise along the Alanya coastline. We anchor at a quiet cove for swimming and BBQ. Drinks and food included. Perfect way to meet fellow travelers.",
    image: "/images/placeholder-business.svg",
    isFeatured: true,
  },
  {
    id: "e3",
    title: "Language Exchange Night",
    date: "2026-06-18",
    day: "18",
    month: "JUN",
    time: "7:00 PM",
    location: "The Local Pub, Alanya",
    category: "Language Exchange Events",
    attendees: 28,
    maxAttendees: 50,
    host: "David Chen",
    hostAvatar: "/images/placeholder-business.svg",
    description: "Practice Turkish, English, German, Russian, and more. All levels welcome. We rotate tables every 20 minutes so you meet everyone. First drink is on us!",
    image: "/images/placeholder-business.svg",
    isFeatured: false,
  },
  {
    id: "e4",
    title: "Hiking the Taurus Mountains",
    date: "2026-06-22",
    day: "22",
    month: "JUN",
    time: "8:00 AM",
    location: "Taurus Mountains Trailhead",
    category: "Hiking Groups",
    attendees: 18,
    maxAttendees: 25,
    host: "Jean-Pierre Laurent",
    hostAvatar: "/images/placeholder-business.svg",
    description: "Moderate 12km trail with stunning Mediterranean views. We stop at a mountain spring for lunch. Bring good shoes, water, and a camera. Transport from Alanya included.",
    image: "/images/placeholder-business.svg",
    isFeatured: false,
  },
  {
    id: "e5",
    title: "Expat Business Networking",
    date: "2026-06-25",
    day: "25",
    month: "JUN",
    time: "6:00 PM",
    location: "Coworking Alanya, Oba",
    category: "Business Networking",
    attendees: 24,
    maxAttendees: 35,
    host: "Sophia Andersson",
    hostAvatar: "/images/placeholder-business.svg",
    description: "Connect with fellow expat entrepreneurs, freelancers, and investors. Short presentations, then open networking with drinks. This month's topic: Turkish tax for foreigners.",
    image: "/images/placeholder-business.svg",
    isFeatured: false,
  },
  {
    id: "e6",
    title: "Full Moon Beach Party",
    date: "2026-06-28",
    day: "28",
    month: "JUN",
    time: "9:00 PM",
    location: "Keykubat Beach, Alanya",
    category: "Beach Gatherings",
    attendees: 78,
    maxAttendees: 120,
    host: "Jake Morrison",
    hostAvatar: "/images/placeholder-business.svg",
    description: "Monthly full moon celebration on the beach. Live DJ, bonfire, and a spectacular moonrise over the Mediterranean. BYOB and bring something to sit on. Everyone welcome!",
    image: "/images/placeholder-business.svg",
    isFeatured: true,
  },
  {
    id: "e7",
    title: "Turkish Cooking Workshop",
    date: "2026-07-02",
    day: "02",
    month: "JUL",
    time: "3:00 PM",
    location: "Zeynep's Kitchen, Alanya",
    category: "Expat Socials",
    attendees: 14,
    maxAttendees: 16,
    host: "Zeynep Kaya",
    hostAvatar: "/images/placeholder-business.svg",
    description: "Learn to make authentic mantı, içli köfte, and baklava from scratch. Small group, hands-on experience. All ingredients provided. You eat what you make! Vegetarian options available.",
    image: "/images/placeholder-business.svg",
    isFeatured: false,
  },
  {
    id: "e8",
    title: "Beach Volleyball Tournament",
    date: "2026-07-06",
    day: "06",
    month: "JUL",
    time: "10:00 AM",
    location: "Cleopatra Beach Courts",
    category: "Sports Activities",
    attendees: 36,
    maxAttendees: 48,
    host: "Ali Karadeniz",
    hostAvatar: "/images/placeholder-business.svg",
    description: "Mixed teams, round-robin format. All skill levels welcome — we make balanced teams. Prizes for winners, cold drinks for everyone. Register as a team or solo.",
    image: "/images/placeholder-business.svg",
    isFeatured: false,
  },
  {
    id: "e9",
    title: "Photography Walk: Old Alanya",
    date: "2026-07-09",
    day: "09",
    month: "JUL",
    time: "9:00 AM",
    location: "Alanya Castle Entrance",
    category: "Hiking Groups",
    attendees: 15,
    maxAttendees: 20,
    host: "Lucas Mueller",
    hostAvatar: "/images/placeholder-business.svg",
    description: "Sunrise photography walk through the old town and castle walls. Bring any camera — phone is fine. I will share composition tips and the best vantage points. Breakfast after.",
    image: "/images/placeholder-business.svg",
    isFeatured: false,
  },
  {
    id: "e10",
    title: "Digital Nomad Coworking Day",
    date: "2026-07-12",
    day: "12",
    month: "JUL",
    time: "9:00 AM",
    location: "Coffice Alanya, Mahmutlar",
    category: "Digital Nomad Events",
    attendees: 32,
    maxAttendees: 50,
    host: "Alex Volkov",
    hostAvatar: "/images/placeholder-business.svg",
    description: "Full day coworking with dedicated desks, fast WiFi, and unlimited coffee. Lunch break together at a local restaurant. End the day with rooftop drinks and networking.",
    image: "/images/placeholder-business.svg",
    isFeatured: false,
  },
  {
    id: "e11",
    title: "Yoga & Meditation on the Beach",
    date: "2026-07-15",
    day: "15",
    month: "JUL",
    time: "7:30 AM",
    location: "İncekum Beach, Alanya",
    category: "Sports Activities",
    attendees: 22,
    maxAttendees: 30,
    host: "Anna Lindström",
    hostAvatar: "/images/placeholder-business.svg",
    description: "Sunrise yoga session suitable for all levels. Gentle flow followed by guided meditation with the sound of waves. Bring your mat or a towel. Healthy smoothie included after.",
    image: "/images/placeholder-business.svg",
    isFeatured: false,
  },
  {
    id: "e12",
    title: "Expat Welcome Dinner",
    date: "2026-07-18",
    day: "18",
    month: "JUL",
    time: "7:00 PM",
    location: "Rooftop Restaurant, Alanya Center",
    category: "Expat Socials",
    attendees: 20,
    maxAttendees: 30,
    host: "Mehmet Demir",
    hostAvatar: "/images/placeholder-business.svg",
    description: "Monthly welcome dinner for newcomers. Meet other expats who just arrived, plus long-term residents who can share tips. Set menu of Turkish mezes and grilled fish. Fixed price 350 TL.",
    image: "/images/placeholder-business.svg",
    isFeatured: false,
  },
  {
    id: "e13",
    title: "Scuba Diving Discovery Day",
    date: "2026-07-21",
    day: "21",
    month: "JUL",
    time: "8:00 AM",
    location: "Alanya Dive Center, Harbor",
    category: "Sports Activities",
    attendees: 10,
    maxAttendees: 12,
    host: "Ali Karadeniz",
    hostAvatar: "/images/placeholder-business.svg",
    description: "Try scuba diving for the first time or refresh your skills. Professional PADI instructors, all equipment provided. Two dives at different sites. No experience needed for beginners.",
    image: "/images/placeholder-business.svg",
    isFeatured: false,
  },
  {
    id: "e14",
    title: "Turkish Tea & Talk: Culture Session",
    date: "2026-07-24",
    day: "24",
    month: "JUL",
    time: "5:00 PM",
    location: "Ahmet's Tea Garden, Alanya",
    category: "Language Exchange Events",
    attendees: 16,
    maxAttendees: 25,
    host: "Ahmet Yılmaz",
    hostAvatar: "/images/placeholder-business.svg",
    description: "Casual weekly gathering to practice Turkish conversation and learn about customs, traditions, and daily life. Native speakers help guide the discussion. Unlimited çay included!",
    image: "/images/placeholder-business.svg",
    isFeatured: false,
  },
  {
    id: "e15",
    title: "Startup Pitch & Pizza Night",
    date: "2026-07-27",
    day: "27",
    month: "JUL",
    time: "6:30 PM",
    location: "Innovation Hub, Alanya",
    category: "Business Networking",
    attendees: 18,
    maxAttendees: 30,
    host: "Alex Volkov",
    hostAvatar: "/images/placeholder-business.svg",
    description: "Casual pitch night for entrepreneurs and side projects. 5-minute pitches, 5-minute Q&A. No pressure, just practice and feedback. Pizza and drinks provided. Come pitch or just watch!",
    image: "/images/placeholder-business.svg",
    isFeatured: false,
  },
  {
    id: "e16",
    title: "Family Fun Day at the Park",
    date: "2026-07-30",
    day: "30",
    month: "JUL",
    time: "11:00 AM",
    location: "Alanya Central Park",
    category: "Traveler Meetups",
    attendees: 25,
    maxAttendees: 50,
    host: "Emma Williams",
    hostAvatar: "/images/placeholder-business.svg",
    description: "Bring the kids for games, face painting, and a picnic. Great chance to meet other families. We will have activities for ages 2-12. Bring a dish to share if you can!",
    image: "/images/placeholder-business.svg",
    isFeatured: false,
  },
  {
    id: "e17",
    title: "Salsa Dancing by the Sea",
    date: "2026-08-03",
    day: "03",
    month: "AUG",
    time: "8:00 PM",
    location: "Beachfront Plaza, Alanya",
    category: "Expat Socials",
    attendees: 40,
    maxAttendees: 80,
    host: "Elena Kowalski",
    hostAvatar: "/images/placeholder-business.svg",
    description: "Open-air salsa night on the beachfront plaza. Beginner lesson at 8pm, open dancing from 9pm. No partner needed — we rotate! Great music, great views, great crowd.",
    image: "/images/placeholder-business.svg",
    isFeatured: true,
  },
  {
    id: "e18",
    title: "Antalya Ancient Cities Road Trip",
    date: "2026-08-07",
    day: "07",
    month: "AUG",
    time: "7:00 AM",
    location: "Departure from Alanya Center",
    category: "Traveler Meetups",
    attendees: 14,
    maxAttendees: 20,
    host: "David Chen",
    hostAvatar: "/images/placeholder-business.svg",
    description: "Full day road trip to Perge, Aspendos, and Side. History buff David will give informal guided tours at each site. Transport in a minibus, lunch at a local restaurant included.",
    image: "/images/placeholder-business.svg",
    isFeatured: false,
  },
  {
    id: "e19",
    title: "Moonlight Kayaking Adventure",
    date: "2026-08-11",
    day: "11",
    month: "AUG",
    time: "8:30 PM",
    location: "Alanya Harbor",
    category: "Sports Activities",
    attendees: 32,
    maxAttendees: 24,
    host: "Ali Karadeniz",
    hostAvatar: "/images/placeholder-business.svg",
    description: "Paddle under the stars along the illuminated Alanya coastline. LED-lit kayaks, gentle waves, and a guide sharing local legends. No experience needed — perfect for couples and small groups.",
    image: "/images/placeholder-business.svg",
    isFeatured: false,
  },
  {
    id: "e20",
    title: "Turkish Coffee & Fortune Telling Night",
    date: "2026-08-14",
    day: "14",
    month: "AUG",
    time: "7:00 PM",
    location: "Kahve Dünyası, Alanya Center",
    category: "Expat Socials",
    attendees: 82,
    maxAttendees: 60,
    host: "Zeynep Kaya",
    hostAvatar: "/images/placeholder-business.svg",
    description: "Sip authentic Turkish coffee brewed on hot sand, then have your fortune read from the coffee grounds. A beloved local tradition — whimsical, social, and surprisingly accurate fun! Limited spots.",
    image: "/images/placeholder-business.svg",
    isFeatured: true,
  },
  {
    id: "e21",
    title: "Paragliding Tandem Day",
    date: "2026-08-18",
    day: "18",
    month: "AUG",
    time: "8:00 AM",
    location: "Alanya Castle Launch Point",
    category: "Sports Activities",
    attendees: 55,
    maxAttendees: 30,
    host: "Mark Stevenson",
    hostAvatar: "/images/placeholder-business.svg",
    description: "Soar over Alanya Castle and Cleopatra Beach with an experienced tandem pilot. Breathtaking 360-degree views of the Mediterranean and Taurus Mountains. GoPro footage included. Pure adrenaline!",
    image: "/images/placeholder-business.svg",
    isFeatured: true,
  },
  {
    id: "e22",
    title: "Expat Pub Quiz Night",
    date: "2026-08-22",
    day: "22",
    month: "AUG",
    time: "7:30 PM",
    location: "The Red Lion Pub, Alanya",
    category: "Expat Socials",
    attendees: 68,
    maxAttendees: 80,
    host: "Emma Williams",
    hostAvatar: "/images/placeholder-business.svg",
    description: "Teams of 4-6 compete in 6 rounds of trivia — general knowledge, music, history, and a surprise round. Great prizes, better banter. Come solo and we will match you with a team!",
    image: "/images/placeholder-business.svg",
    isFeatured: false,
  },
  {
    id: "e23",
    title: "Dim River BBQ & Cliff Jumping",
    date: "2026-08-27",
    day: "27",
    month: "AUG",
    time: "10:00 AM",
    location: "Dimçayı River, Alanya",
    category: "Traveler Meetups",
    attendees: 47,
    maxAttendees: 50,
    host: "Jake Morrison",
    hostAvatar: "/images/placeholder-business.svg",
    description: "Escape the heat at the lush Dim River. Floating platforms, ice-cold mountain water, cliff jumping spots, and a riverside BBQ feast. Transport and lunch included. Bring swimwear and courage!",
    image: "/images/placeholder-business.svg",
    isFeatured: false,
  },
  {
    id: "e24",
    title: "Backgammon Tournament Under the Stars",
    date: "2026-08-31",
    day: "31",
    month: "AUG",
    time: "8:00 PM",
    location: "Rooftop Terrace, Alanya Center",
    category: "Language Exchange Events",
    attendees: 25,
    maxAttendees: 32,
    host: "Ahmet Yılmaz",
    hostAvatar: "/images/placeholder-business.svg",
    description: "Tavla (backgammon) is Turkey's national obsession. Learn the basics or compete in our friendly knockout tournament. Çay, nargile, and good company under the stars. All levels welcome!",
    image: "/images/placeholder-business.svg",
    isFeatured: false,
  },
  {
    id: "e25",
    title: "Cappadocia Weekend Getaway",
    date: "2026-09-05",
    day: "05",
    month: "SEP",
    time: "6:00 AM",
    location: "Departure from Alanya Center",
    category: "Traveler Meetups",
    attendees: 94,
    maxAttendees: 40,
    host: "David Chen",
    hostAvatar: "/images/placeholder-business.svg",
    description: "Two-day trip to the fairy chimneys of Cappadocia. Hot air balloon ride at sunrise, underground city tour, pottery workshop, and cave hotel stay. THE bucket-list Turkey experience — don't miss it!",
    image: "/images/placeholder-business.svg",
    isFeatured: true,
  },
  {
    id: "e26",
    title: "Sunset Bike Tour: Alanya Coastline",
    date: "2026-09-10",
    day: "10",
    month: "SEP",
    time: "5:30 PM",
    location: "Alanya Bike Rental, Harbor",
    category: "Sports Activities",
    attendees: 20,
    maxAttendees: 20,
    host: "Lucas Mueller",
    hostAvatar: "/images/placeholder-business.svg",
    description: "15km coastal bike ride from the harbor to İncekum Beach and back — all flat, all scenic. Stop for sunset photos and a well-earned ice cream. Bikes and helmets provided. Easy pace, social vibes.",
    image: "/images/placeholder-business.svg",
    isFeatured: false,
  },
  {
    id: "e27",
    title: "Turkish Wine Tasting Evening",
    date: "2026-09-14",
    day: "14",
    month: "SEP",
    time: "6:30 PM",
    location: "Vinoteka Alanya, City Center",
    category: "Expat Socials",
    attendees: 75,
    maxAttendees: 35,
    host: "Sophia Andersson",
    hostAvatar: "/images/placeholder-business.svg",
    description: "Discover Turkey's emerging wine scene. Guided tasting of 8 Anatolian wines paired with local cheeses and mezes. Learn about indigenous grapes like Öküzgözü and Boğazkere. Sophisticated and social.",
    image: "/images/placeholder-business.svg",
    isFeatured: false,
  },
  {
    id: "e28",
    title: "Kite Surfing Intro Weekend",
    date: "2026-09-19",
    day: "19",
    month: "SEP",
    time: "9:00 AM",
    location: "İncekum Beach, Alanya",
    category: "Sports Activities",
    attendees: 38,
    maxAttendees: 16,
    host: "Alex Volkov",
    hostAvatar: "/images/placeholder-business.svg",
    description: "Two-day beginner kite surfing course with IKO-certified instructors. Day 1: theory and kite control on the beach. Day 2: body dragging and first board starts. All equipment provided. Wind guaranteed!",
    image: "/images/placeholder-business.svg",
    isFeatured: false,
  },
  {
    id: "e29",
    title: "Ebru Art & Turkish Calligraphy Workshop",
    date: "2026-09-24",
    day: "24",
    month: "SEP",
    time: "2:00 PM",
    location: "Alanya Cultural Center",
    category: "Language Exchange Events",
    attendees: 48,
    maxAttendees: 20,
    host: "Mehmet Demir",
    hostAvatar: "/images/placeholder-business.svg",
    description: "Learn the mesmerizing art of Ebru — Turkish paper marbling. Create your own floating masterpieces on water, then transfer them to paper. Includes a calligraphy session with traditional reed pens. Frame-worthy results!",
    image: "/images/placeholder-business.svg",
    isFeatured: false,
  },
  {
    id: "e30",
    title: "End of Summer Beach Bonfire Gala",
    date: "2026-09-30",
    day: "30",
    month: "SEP",
    time: "7:00 PM",
    location: "Keykubat Beach, Alanya",
    category: "Beach Gatherings",
    attendees: 110,
    maxAttendees: 150,
    host: "Elena Kowalski",
    hostAvatar: "/images/placeholder-business.svg",
    description: "Our biggest event of the year! Massive bonfire, live acoustic band, fire dancers, and a farewell-to-summer beach feast. Bring blankets, drinks, and your best summer stories. The whole community comes together for this one.",
    image: "/images/placeholder-business.svg",
    isFeatured: true,
  },
];

export const eventCategories = [
  "Digital Nomad Events",
  "Beach Gatherings",
  "Language Exchange Events",
  "Hiking Groups",
  "Business Networking",
  "Expat Socials",
  "Sports Activities",
  "Traveler Meetups",
];