export interface Villa {
  id: string;
  name: string;
  location: string;
  bedrooms: number;
  bathrooms: number;
  maxGuests: number;
  pricePerNight: number;
  currency: string;
  hasPool: boolean;
  hasSeaView: boolean;
  image: string;
  description: string;
  amenities: string[];
  rating: number;
  reviewCount: number;
  featured: boolean;
  minStay: number;
  distanceToBeach: string;
  type?: string;
  images?: string[];
}

export const villaLocations = [
  { id: "all", name: "All Locations", icon: "ri-map-pin-line" },
  { id: "alanya-center", name: "Alanya Center", icon: "ri-building-line" },
  { id: "mahmutlar", name: "Mahmutlar", icon: "ri-home-4-line" },
  { id: "kargicak", name: "Kargıcak", icon: "ri-landscape-line" },
  { id: "konakli", name: "Konaklı", icon: "ri-hotel-line" },
  { id: "tosmur", name: "Tosmur", icon: "ri-community-line" },
];

export const villas: Villa[] = [
  {
    id: "villa-001",
    name: "Villa Azure",
    location: "Mahmutlar",
    bedrooms: 5,
    bathrooms: 4,
    maxGuests: 10,
    pricePerNight: 420,
    currency: "EUR",
    hasPool: true,
    hasSeaView: true,
    image: "/images/placeholder-business.svg",
    description: "Villa Azure is a stunning contemporary retreat perched on the hills of Mahmutlar with uninterrupted panoramic sea views. Five generously sized bedrooms, an infinity pool that seems to merge with the Mediterranean, and a shaded pergola dining area make this the ultimate group escape. Every detail, from the Italian marble floors to the handcrafted wooden ceilings, speaks of uncompromising quality.",
    amenities: ["Infinity Pool", "Sea View", "Air Conditioning", "WiFi", "BBQ", "Private Parking", "Fully Equipped Kitchen", "Outdoor Dining", "Sun Loungers", "Washing Machine", "Satellite TV", "Garden"],
    rating: 4.9,
    reviewCount: 34,
    featured: true,
    minStay: 3,
    distanceToBeach: "800m",
  },
  {
    id: "villa-002",
    name: "Kleopatra Pearl",
    location: "Alanya Center",
    bedrooms: 3,
    bathrooms: 2,
    maxGuests: 6,
    pricePerNight: 280,
    currency: "EUR",
    hasPool: true,
    hasSeaView: false,
    image: "/images/placeholder-business.svg",
    description: "Just a five-minute stroll from the legendary Cleopatra Beach, Kleopatra Pearl offers the best of both worlds — beach proximity and private tranquility. This beautifully restored three-bedroom villa wraps around a courtyard pool, with fragrant jasmine and bougainvillea framing every window. The rooftop terrace is the perfect spot for sunset drinks before heading out to explore Alanya's vibrant old town.",
    amenities: ["Private Pool", "Air Conditioning", "WiFi", "BBQ", "Rooftop Terrace", "Fully Equipped Kitchen", "Courtyard", "Sun Loungers", "Washing Machine", "Beach Towels"],
    rating: 4.8,
    reviewCount: 52,
    featured: true,
    minStay: 2,
    distanceToBeach: "300m",
  },
  {
    id: "villa-003",
    name: "Mountain Olive Estate",
    location: "Kargıcak",
    bedrooms: 6,
    bathrooms: 5,
    maxGuests: 12,
    pricePerNight: 650,
    currency: "EUR",
    hasPool: true,
    hasSeaView: true,
    image: "/images/placeholder-business.svg",
    description: "Set within its own olive grove in the exclusive Kargıcak hills, Mountain Olive Estate is a sanctuary of space and serenity. Six en-suite bedrooms, a 16-meter infinity pool, a private cinema room, and a professional-grade kitchen make it ideal for multigenerational family gatherings or corporate retreats. The estate produces its own olive oil — every guest leaves with a bottle.",
    amenities: ["Infinity Pool", "Cinema Room", "Sea View", "Air Conditioning", "WiFi", "BBQ", "Private Parking", "Chef's Kitchen", "Olive Grove", "Outdoor Dining", "Fireplace", "Garden", "Concierge Service"],
    rating: 5.0,
    reviewCount: 18,
    featured: true,
    minStay: 5,
    distanceToBeach: "1.2km",
  },
  {
    id: "villa-004",
    name: "Turquoise Garden Villa",
    location: "Konaklı",
    bedrooms: 4,
    bathrooms: 3,
    maxGuests: 8,
    pricePerNight: 320,
    currency: "EUR",
    hasPool: true,
    hasSeaView: true,
    image: "/images/placeholder-business.svg",
    description: "Turquoise Garden Villa lives up to its name — the pool's vivid blue is matched only by the sea view from the upper balcony. Four bright, airy bedrooms, a sprawling garden with a hammock grove, and a covered outdoor kitchen and dining area. Located in the peaceful Konaklı district, you're close enough to the action but far enough to forget the world exists.",
    amenities: ["Private Pool", "Sea View", "Air Conditioning", "WiFi", "BBQ", "Private Parking", "Outdoor Kitchen", "Garden", "Hammock", "Sun Loungers", "Washing Machine", "Satellite TV"],
    rating: 4.7,
    reviewCount: 41,
    featured: false,
    minStay: 3,
    distanceToBeach: "600m",
  },
  {
    id: "villa-005",
    name: "Casa del Mar",
    location: "Tosmur",
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    pricePerNight: 190,
    currency: "EUR",
    hasPool: false,
    hasSeaView: true,
    image: "/images/placeholder-business.svg",
    description: "Casa del Mar is the romantic getaway you've been dreaming of. This intimate two-bedroom villa in Tosmur sits right above the coastline, with a vast terrace that makes you feel like you're floating over the sea. Floor-to-ceiling sliding doors blur the line between indoors and outdoors. Perfect for couples or small families seeking peace, privacy, and those endless Mediterranean sunsets.",
    amenities: ["Sea View", "Air Conditioning", "WiFi", "Private Parking", "Fully Equipped Kitchen", "Terrace", "Sun Loungers", "Washing Machine", "Satellite TV", "BBQ"],
    rating: 4.9,
    reviewCount: 29,
    featured: false,
    minStay: 2,
    distanceToBeach: "150m",
  },
  {
    id: "villa-006",
    name: "Palm Oasis Retreat",
    location: "Mahmutlar",
    bedrooms: 4,
    bathrooms: 3,
    maxGuests: 8,
    pricePerNight: 360,
    currency: "EUR",
    hasPool: true,
    hasSeaView: true,
    image: "/images/placeholder-business.svg",
    description: "Palm Oasis Retreat combines resort-style living with the privacy of a standalone villa. Four spacious bedrooms, a palm-fringed pool, and an open-plan living area that flows seamlessly to the garden. The villa comes with a dedicated housekeeper who prepares a traditional Turkish breakfast each morning — included in the rate. It is the kind of place where you arrive stressed and leave wondering why you didn't book longer.",
    amenities: ["Private Pool", "Sea View", "Air Conditioning", "WiFi", "BBQ", "Private Parking", "Daily Breakfast", "Housekeeper", "Fully Equipped Kitchen", "Garden", "Sun Loungers", "Washing Machine"],
    rating: 4.8,
    reviewCount: 37,
    featured: false,
    minStay: 3,
    distanceToBeach: "500m",
  },
  {
    id: "villa-007",
    name: "Beyaz Saray Villa",
    location: "Alanya Center",
    bedrooms: 7,
    bathrooms: 6,
    maxGuests: 14,
    pricePerNight: 850,
    currency: "EUR",
    hasPool: true,
    hasSeaView: true,
    image: "/images/placeholder-business.svg",
    description: "Beyaz Saray — the 'White Palace' — is the most exclusive villa in our collection. Seven luxurious bedrooms, each with an en-suite marble bathroom and private balcony. The 20-meter infinity pool appears to cascade into the Mediterranean, with Alanya Castle providing a dramatic backdrop. A private chef, butler service, and daily housekeeping are included. This is where you host the celebration of a lifetime.",
    amenities: ["Infinity Pool", "Sea View", "Castle View", "Air Conditioning", "WiFi", "BBQ", "Private Parking", "Private Chef", "Butler Service", "Housekeeper", "Cinema Room", "Wine Cellar", "Gym", "Sauna", "Garden"],
    rating: 5.0,
    reviewCount: 12,
    featured: true,
    minStay: 7,
    distanceToBeach: "400m",
  },
  {
    id: "villa-008",
    name: "Zen Garden House",
    location: "Kargıcak",
    bedrooms: 3,
    bathrooms: 2,
    maxGuests: 6,
    pricePerNight: 250,
    currency: "EUR",
    hasPool: true,
    hasSeaView: false,
    image: "/images/placeholder-business.svg",
    description: "Zen Garden House is unlike anything else on the Turkish Riviera. The Japanese-Turkish fusion design creates a uniquely calming atmosphere — a koi pond beside olive trees, tatami-inspired bedrooms with Anatolian kilims, and a saltwater pool surrounded by bamboo. Three bedrooms, a meditation pavilion, and absolute silence except for birdsong and the breeze through the pines.",
    amenities: ["Saltwater Pool", "Air Conditioning", "WiFi", "BBQ", "Private Parking", "Zen Garden", "Koi Pond", "Meditation Pavilion", "Fully Equipped Kitchen", "Fireplace", "Washing Machine", "Satellite TV"],
    rating: 4.9,
    reviewCount: 23,
    featured: false,
    minStay: 3,
    distanceToBeach: "2km",
  },
  {
    id: "villa-009",
    name: "Sunkissed Terrace",
    location: "Konaklı",
    bedrooms: 2,
    bathrooms: 1,
    maxGuests: 4,
    pricePerNight: 150,
    currency: "EUR",
    hasPool: false,
    hasSeaView: true,
    image: "/images/placeholder-business.svg",
    description: "Sunkissed Terrace proves that luxury doesn't need to be massive. This beautifully designed two-bedroom villa maximizes its hillside position with a vast, private sun terrace that catches light from dawn to dusk. Simple, stylish interiors, a well-equipped kitchen, and the best-value sea view in Konaklı. Ideal for couples or solo travelers who want their own slice of the Riviera without the premium price tag.",
    amenities: ["Sea View", "Air Conditioning", "WiFi", "Private Parking", "Fully Equipped Kitchen", "Sun Terrace", "Outdoor Dining", "Washing Machine", "Satellite TV"],
    rating: 4.6,
    reviewCount: 48,
    featured: false,
    minStay: 2,
    distanceToBeach: "900m",
  },
];