export interface CrewMember {
  name: string;
  role: string;
  experience: string;
  bio: string;
  image: string;
}

export interface Yacht {
  id: string;
  name: string;
  company: string;
  type: "Gulet" | "Motor Yacht" | "Catamaran" | "Sailing Yacht" | "Luxury Yacht";
  capacity: number;
  cabins: number;
  length: string;
  year: number;
  pricePerDay: number;
  currency: string;
  halfDayPrice: number;
  image: string;
  description: string;
  amenities: string[];
  crewIncluded: boolean;
  skipperRequired: boolean;
  rating: number;
  reviewCount: number;
  availableRoutes: string[];
  featured: boolean;
  port: string;
  crew: CrewMember[];
}

export const yachtTypes = [
  { id: "all", name: "All Yachts", icon: "ri-ship-line" },
  { id: "gulet", name: "Gulets", icon: "ri-anchor-line" },
  { id: "motor-yacht", name: "Motor Yachts", icon: "ri-ship-2-fill" },
  { id: "catamaran", name: "Catamarans", icon: "ri-sailboat-line" },
  { id: "sailing-yacht", name: "Sailing Yachts", icon: "ri-compass-3-line" },
  { id: "luxury-yacht", name: "Luxury Yachts", icon: "ri-vip-crown-line" },
];

export const yachts: Yacht[] = [
  {
    id: "yacht-001",
    name: "Aegean Queen",
    company: "Era Yachting",
    type: "Gulet",
    capacity: 12,
    cabins: 6,
    length: "28m",
    year: 2019,
    pricePerDay: 850,
    currency: "EUR",
    halfDayPrice: 450,
    image: "https://readdy.ai/api/search-image?query=Luxurious%20traditional%20Turkish%20wooden%20gulet%20yacht%20anchored%20in%20crystal%20clear%20turquoise%20cove%20Mediterranean%20coast%20spacious%20teak%20deck%20with%20white%20sun%20cushions%20elegant%20nautical%20design%20white%20hull%20warm%20golden%20afternoon%20light%20serene%20atmosphere%20editorial%20photography%20high%20detail&width=900&height=675&seq=yacht-gulet-001&orientation=landscape",
    description: "A masterpiece of traditional Turkish boatbuilding, the Aegean Queen blends classic gulet charm with modern luxury. Six en-suite cabins accommodate up to 12 guests in comfort, with a spacious saloon, fully equipped galley, and expansive deck areas perfect for sunbathing and al fresco dining. The professional crew of three ensures every moment aboard is pure bliss.",
    amenities: ["Air Conditioning", "WiFi", "Snorkeling Gear", "Fishing Equipment", "Sound System", "Chef Onboard", "Water Toys", "Sun Deck", "BBQ", "Ice Maker"],
    crewIncluded: true,
    skipperRequired: false,
    rating: 4.9,
    reviewCount: 86,
    availableRoutes: ["Alanya Coastline", "Alanya to Antalya", "Alanya to Cyprus", "Hidden Coves Tour"],
    featured: true,
    port: "Alanya Marina",
    crew: [
      {
        name: "Captain Mehmet Yılmaz",
        role: "Captain",
        experience: "18+ years at sea",
        bio: "Born in Bodrum to a family of shipwrights, Mehmet has sailed the Turkish Riviera since he was a boy. His encyclopedic knowledge of hidden coves and calm anchorages between Alanya and Antalya makes every voyage feel like a discovery. Guests often say his warm laugh and endless stories are the highlight of the trip.",
        image: "https://readdy.ai/api/search-image?query=Distinguished%20Turkish%20man%20in%20his%20early%20fifties%20with%20salt%20and%20pepper%20hair%20and%20a%20neatly%20trimmed%20beard%20wearing%20a%20crisp%20white%20captain%20shirt%20with%20gold%20epaulettes%20standing%20on%20the%20deck%20of%20a%20traditional%20wooden%20gulet%20warm%20Mediterranean%20sunset%20in%20background%20kind%20wise%20expression%20professional%20maritime%20portrait%20photography%20natural%20lighting&width=400&height=500&seq=crew-captain-mehmet&orientation=portrait",
      },
      {
        name: "Aylin Kaya",
        role: "Chef",
        experience: "10+ years in galley kitchens",
        bio: "Aylin trained at culinary school in Istanbul before falling in love with cooking at sea. Her mezze platters are legendary among returning guests, and she sources fresh fish, olives, and produce from the coastal villages you'll visit. Dietary restrictions? She considers them a creative challenge, not a problem.",
        image: "https://readdy.ai/api/search-image?query=Turkish%20woman%20in%20her%20late%20thirties%20with%20warm%20brown%20eyes%20and%20dark%20hair%20tied%20back%20in%20a%20loose%20bun%20wearing%20a%20white%20chef%20jacket%20smiling%20naturally%20while%20standing%20in%20a%20boat%20galley%20kitchen%20with%20fresh%20vegetables%20and%20herbs%20on%20the%20counter%20soft%20natural%20daylight%20professional%20portrait%20photography%20genuine%20expression&width=400&height=500&seq=crew-chef-aylin&orientation=portrait",
      },
    ],
  },
  {
    id: "yacht-002",
    name: "Turquoise Dream",
    company: "Turk Yacht",
    type: "Motor Yacht",
    capacity: 8,
    cabins: 4,
    length: "22m",
    year: 2021,
    pricePerDay: 1200,
    currency: "EUR",
    halfDayPrice: 650,
    image: "https://readdy.ai/api/search-image?query=Sleek%20modern%20white%20motor%20yacht%20cruising%20on%20deep%20blue%20Mediterranean%20sea%20dramatic%20Taurus%20mountains%20coastline%20in%20background%20sunny%20day%20wake%20trailing%20behind%20luxury%20vessel%20powerful%20design%20editorial%20yachting%20photography%20crisp%20clean%20aesthetic&width=900&height=675&seq=yacht-motor-002&orientation=landscape",
    description: "Speed meets elegance aboard the Turquoise Dream. This Italian-designed motor yacht delivers thrilling performance with a cruising speed of 24 knots, letting you explore more of the coastline in less time. Four luxurious cabins, a flybridge with panoramic views, and a hydraulic swimming platform make this the ultimate choice for day charters and short escapes.",
    amenities: ["Air Conditioning", "WiFi", "Jet Ski", "Snorkeling Gear", "Flybridge", "Swim Platform", "Sound System", "Sun Deck", "Water Ski", "Towable Tube"],
    crewIncluded: true,
    skipperRequired: false,
    rating: 4.8,
    reviewCount: 62,
    availableRoutes: ["Alanya Coastline", "Alanya to Side", "Alanya to Gazipaşa", "Sunset Cruise"],
    featured: true,
    port: "Alanya Marina",
    crew: [
      {
        name: "Captain Deniz Kara",
        role: "Captain",
        experience: "12+ years at sea",
        bio: "A former Turkish naval officer, Deniz brings military precision and calm confidence to every charter. He transitioned to luxury yachting a decade ago and never looked back. His sharp navigation skills mean you'll reach the best swim spots before the crowds, and his dry wit keeps the atmosphere relaxed all day.",
        image: "https://readdy.ai/api/search-image?query=Turkish%20man%20in%20his%20early%20forties%20with%20short%20dark%20hair%20and%20a%20confident%20composed%20expression%20wearing%20a%20navy%20blue%20polo%20shirt%20with%20captain%20insignia%20standing%20at%20the%20helm%20of%20a%20modern%20motor%20yacht%20bright%20Mediterranean%20sunlight%20streaming%20through%20the%20bridge%20windows%20professional%20portrait%20photography%20clean%20sharp%20focus&width=400&height=500&seq=crew-captain-deniz&orientation=portrait",
      },
      {
        name: "Emre Can",
        role: "First Mate & Water Sports Instructor",
        experience: "8+ years",
        bio: "Emre is the energy behind every charter — part deckhand, part water sports coach, and full-time vibe curator. He'll have you up on waterskis within an hour (or buying him a beer for trying), and his snorkeling tours reveal the best underwater spots along the coast. Speaks fluent English and German.",
        image: "https://readdy.ai/api/search-image?query=Friendly%20Turkish%20man%20in%20his%20early%20thirties%20with%20sun-bleached%20brown%20hair%20and%20a%20tanned%20athletic%20build%20wearing%20a%20casual%20white%20linen%20shirt%20on%20the%20deck%20of%20a%20yacht%20holding%20snorkeling%20gear%20bright%20sunny%20day%20turquoise%20sea%20background%20warm%20genuine%20smile%20adventure%20lifestyle%20portrait%20photography&width=400&height=500&seq=crew-mate-emre&orientation=portrait",
      },
    ],
  },
  {
    id: "yacht-003",
    name: "Mediterranean Star",
    company: "Sirena Yachting Alanya",
    type: "Catamaran",
    capacity: 16,
    cabins: 8,
    length: "42ft",
    year: 2022,
    pricePerDay: 1100,
    currency: "EUR",
    halfDayPrice: 600,
    image: "https://readdy.ai/api/search-image?query=Spacious%20modern%20sailing%20catamaran%20with%20white%20hull%20and%20trampoline%20nets%20anchored%20in%20calm%20turquoise%20bay%20Mediterranean%20sea%20clear%20water%20visible%20sandy%20bottom%20two%20hulls%20stable%20design%20sunny%20day%20luxury%20lifestyle%20photography%20high%20detail&width=900&height=675&seq=yacht-cat-003&orientation=landscape",
    description: "The Mediterranean Star is a state-of-the-art sailing catamaran offering the perfect blend of stability, space, and luxury. With eight cabins, a massive flybridge lounge, and wide-open deck spaces, it is the ideal choice for large groups, corporate events, or family reunions. The shallow draft allows access to secluded bays that deeper vessels cannot reach.",
    amenities: ["Air Conditioning", "WiFi", "Snorkeling Gear", "Kayaks", "Paddleboards", "Sound System", "Chef Onboard", "Flybridge", "BBQ", "Wine Cellar"],
    crewIncluded: true,
    skipperRequired: false,
    rating: 4.7,
    reviewCount: 48,
    availableRoutes: ["Alanya Coastline", "Alanya to Antalya", "Blue Cave Tour", "Island Hopping"],
    featured: true,
    port: "Alanya Marina",
    crew: [
      {
        name: "Captain Elena Rossi",
        role: "Captain",
        experience: "14+ years at sea",
        bio: "Originally from the Amalfi Coast, Elena grew up on her grandfather's fishing boat and earned her captain's license before she could drive a car. She's sailed catamarans across three oceans and settled on the Turkish Riviera for its unmatched combination of reliable winds, warm waters, and ancient coastline. Fluent in Italian, English, and conversational Turkish.",
        image: "https://readdy.ai/api/search-image?query=Italian%20woman%20in%20her%20early%20forties%20with%20sun-kissed%20olive%20skin%20and%20wavy%20brown%20hair%20tied%20in%20a%20practical%20ponytail%20wearing%20a%20white%20captain%20polo%20shirt%20standing%20at%20the%20helm%20of%20a%20catamaran%20bright%20blue%20sky%20and%20sea%20in%20background%20confident%20warm%20smile%20professional%20maritime%20portrait%20photography%20natural%20daylight&width=400&height=500&seq=crew-captain-elena&orientation=portrait",
      },
      {
        name: "Marco Bianchi",
        role: "Chef",
        experience: "15+ years in professional kitchens",
        bio: "Marco left a promising restaurant career in Bologna to cook at sea, and he'll tell you it was the best decision of his life. His Mediterranean fusion menus change daily based on what's fresh at the morning fish market. Homemade pasta rolled by hand on deck, grilled octopus, and his signature limoncello tiramisu are not to be missed.",
        image: "https://readdy.ai/api/search-image?query=Italian%20man%20in%20his%20mid%20forties%20with%20dark%20hair%20and%20a%20neatly%20kept%20beard%20wearing%20a%20white%20chef%20apron%20over%20a%20casual%20linen%20shirt%20standing%20on%20a%20boat%20deck%20with%20a%20wooden%20platter%20of%20fresh%20Mediterranean%20seafood%20bright%20sunny%20day%20genuine%20warm%20expression%20lifestyle%20portrait%20photography&width=400&height=500&seq=crew-chef-marco&orientation=portrait",
      },
    ],
  },
  {
    id: "yacht-004",
    name: "Wind Whisper",
    company: "Vela Mare Alanya",
    type: "Sailing Yacht",
    capacity: 6,
    cabins: 3,
    length: "46ft",
    year: 2020,
    pricePerDay: 680,
    currency: "EUR",
    halfDayPrice: 380,
    image: "https://readdy.ai/api/search-image?query=Elegant%20white%20sailing%20yacht%20with%20full%20sails%20raised%20gliding%20across%20deep%20blue%20Mediterranean%20water%20dramatic%20Alanya%20castle%20silhouette%20on%20rocky%20peninsula%20in%20background%20golden%20hour%20sunset%20lighting%20romantic%20atmosphere%20editorial%20sailing%20photography%20breathtaking%20scene&width=900&height=675&seq=yacht-sail-004&orientation=landscape",
    description: "For the purist, nothing compares to the sound of wind in the sails. Wind Whisper is a performance cruising yacht that delivers an authentic sailing experience without sacrificing comfort. Three cozy cabins, a well-appointed galley, and a cockpit designed for sunset dinners. You can take the helm yourself or let our experienced skipper handle the sailing while you relax.",
    amenities: ["Autopilot", "Snorkeling Gear", "Fishing Equipment", "Sound System", "Cockpit Dining", "Sun Deck", "Chart Plotter", "Dinghy"],
    crewIncluded: false,
    skipperRequired: true,
    rating: 4.8,
    reviewCount: 39,
    availableRoutes: ["Alanya Coastline", "Sunset Sailing", "Alanya to Gazipaşa", "Overnight Adventure"],
    featured: false,
    port: "Alanya Marina",
    crew: [
      {
        name: "Captain Kaan Demir",
        role: "Skipper",
        experience: "20+ years at sea",
        bio: "Kaan is the sailor other skippers call for advice. With two decades navigating the Mediterranean and Aegean, he reads the wind like a language. Available as a hired skipper for Wind Whisper, he's equally happy handing you the helm and coaching your technique or handling everything himself while you soak up the sun. His sunset anchorage recommendations are worth the charter alone.",
        image: "https://readdy.ai/api/search-image?query=Rugged%20Turkish%20man%20in%20his%20fifties%20with%20weathered%20tan%20skin%20and%20graying%20windswept%20hair%20wearing%20a%20faded%20navy%20sweater%20standing%20at%20the%20wheel%20of%20a%20sailing%20yacht%20deep%20blue%20sea%20behind%20him%20wise%20calm%20eyes%20looking%20toward%20the%20horizon%20golden%20hour%20lighting%20professional%20portrait%20photography%20authentic%20maritime%20character&width=400&height=500&seq=crew-captain-kaan&orientation=portrait",
      },
    ],
  },
  {
    id: "yacht-005",
    name: "Poseidon's Palace",
    company: "Mare Nostrum Charters",
    type: "Luxury Yacht",
    capacity: 10,
    cabins: 5,
    length: "35m",
    year: 2022,
    pricePerDay: 2800,
    currency: "EUR",
    halfDayPrice: 1500,
    image: "https://readdy.ai/api/search-image?query=Magnificent%20super%20yacht%20with%20sleek%20modern%20design%20anchored%20off%20Mediterranean%20coast%20at%20golden%20hour%20warm%20sunset%20light%20reflecting%20on%20polished%20white%20hull%20and%20glass%20surfaces%20jacuzzi%20on%20deck%20luxury%20tender%20boat%20alongside%20opulent%20lifestyle%20editorial%20yachting%20photography%20premium%20quality&width=900&height=675&seq=yacht-luxury-005&orientation=landscape",
    description: "The crown jewel of Alanya's charter fleet. Poseidon's Palace is a tri-deck superyacht that redefines luxury on the Turkish Riviera. Five staterooms with marble bathrooms, a Jacuzzi on the sun deck, a cinema room, and a private chef crafting bespoke menus. A dedicated crew of five delivers seven-star service. This is not a boat — it is a floating palace.",
    amenities: ["Jacuzzi", "Cinema Room", "Air Conditioning", "WiFi", "Jet Ski", "Snorkeling Gear", "Chef Onboard", "Butler Service", "Wine Cellar", "Gym Equipment", "Water Toys", "Tender Boat"],
    crewIncluded: true,
    skipperRequired: false,
    rating: 5.0,
    reviewCount: 28,
    availableRoutes: ["Alanya to Antalya", "Alanya to Cyprus", "Turkish Riviera Grand Tour", "Bespoke Custom Route"],
    featured: true,
    port: "Alanya Marina",
    crew: [
      {
        name: "Captain Viktor Petrov",
        role: "Captain",
        experience: "25+ years at sea",
        bio: "Viktor has commanded superyachts from the Caribbean to the Seychelles and now calls the Turkish Riviera home. A graduate of the Odessa Maritime Academy, he leads his crew of five with quiet authority and old-world professionalism. His pre-charter briefings are thorough, his anchorage selections impeccable, and his ability to make every guest feel like the owner is unrivaled.",
        image: "https://readdy.ai/api/search-image?query=Distinguished%20man%20in%20his%20late%20fifties%20with%20silver-gray%20hair%20and%20a%20well-groomed%20beard%20wearing%20an%20immaculate%20white%20captain%20uniform%20with%20four%20gold%20stripes%20standing%20on%20the%20bridge%20of%20a%20luxury%20superyacht%20panoramic%20windows%20revealing%20sunset%20over%20the%20Mediterranean%20authoritative%20yet%20warm%20presence%20professional%20maritime%20portrait%20photography%20premium%20quality&width=400&height=500&seq=crew-captain-viktor&orientation=portrait",
      },
      {
        name: "Isabella Conti",
        role: "Chef",
        experience: "18+ years in Michelin-starred kitchens",
        bio: "Roman-born Isabella spent twelve years in Michelin-starred restaurants across Italy and France before bringing her talents to the superyacht world. She personally designs each menu with guests before departure — no fixed menus, no compromises. Her saffron risotto, hand-rolled truffle pasta, and deconstructed tiramisu have guests booking return charters before dessert arrives.",
        image: "https://readdy.ai/api/search-image?query=Elegant%20Italian%20woman%20in%20her%20mid%20forties%20with%20dark%20hair%20swept%20into%20a%20neat%20chignon%20wearing%20a%20pristine%20white%20chef%20jacket%20with%20subtle%20gold%20embroidery%20standing%20in%20a%20bright%20modern%20galley%20kitchen%20on%20a%20luxury%20yacht%20soft%20natural%20light%20confident%20composed%20expression%20culinary%20professional%20portrait%20photography&width=400&height=500&seq=crew-chef-isabella&orientation=portrait",
      },
      {
        name: "Alexei Volkov",
        role: "Chief Steward",
        experience: "12+ years in luxury hospitality",
        bio: "Alexei trained at five-star hotels in St. Petersburg and Dubai before transitioning to yachting, and it shows in every detail. From perfectly chilled champagne appearing the moment you step on deck to fresh flowers in every cabin, his attention to detail is borderline telepathic. He mixes a mean Negroni and remembers every guest's preference, even if you only mentioned it once.",
        image: "https://readdy.ai/api/search-image?query=Polished%20Eastern%20European%20man%20in%20his%20late%20thirties%20with%20short%20neat%20dark%20blonde%20hair%20wearing%20a%20crisp%20white%20short-sleeve%20steward%20shirt%20with%20a%20bow%20tie%20standing%20on%20a%20superyacht%20deck%20holding%20a%20silver%20serving%20tray%20with%20champagne%20glasses%20Mediterranean%20sea%20background%20warm%20professional%20smile%20luxury%20service%20portrait%20photography&width=400&height=500&seq=crew-steward-alexei&orientation=portrait",
      },
    ],
  },
  {
    id: "yacht-006",
    name: "Ottoman Breeze",
    company: "Alanya Mavi Yachting",
    type: "Gulet",
    capacity: 10,
    cabins: 5,
    length: "24m",
    year: 2017,
    pricePerDay: 650,
    currency: "EUR",
    halfDayPrice: 350,
    image: "https://readdy.ai/api/search-image?query=Beautifully%20crafted%20wooden%20Turkish%20gulet%20with%20rich%20mahogany%20deck%20and%20white%20cushions%20anchored%20in%20secluded%20Mediterranean%20cove%20surrounded%20by%20pine-covered%20hills%20calm%20turquoise%20water%20rustic%20elegance%20traditional%20craftsmanship%20editorial%20photography%20warm%20natural%20tones&width=900&height=675&seq=yacht-gulet-006&orientation=landscape",
    description: "Ottoman Breeze is a lovingly maintained traditional gulet built by one of Bodrum's most respected master shipwrights. Rich mahogany woodwork, hand-carved details, and soft white cushions create an atmosphere of timeless elegance. Five cabins with private bathrooms, a shaded aft deck for meals, and a crew that treats you like family. The best value in the fleet.",
    amenities: ["Air Conditioning", "WiFi", "Snorkeling Gear", "Fishing Equipment", "Sound System", "Chef Onboard", "Sun Deck", "BBQ", "Board Games"],
    crewIncluded: true,
    skipperRequired: false,
    rating: 4.7,
    reviewCount: 71,
    availableRoutes: ["Alanya Coastline", "Seven Capes Tour", "Moonlight Cruise", "Family Adventure"],
    featured: false,
    port: "Alanya Marina",
    crew: [
      {
        name: "Captain Osman Şahin",
        role: "Captain",
        experience: "22+ years at sea",
        bio: "Osman was born into Bodrum's legendary shipbuilding community — his father and grandfather both built gulets by hand. He knows these wooden beauties inside and out, and his deep, rumbling voice telling stories of ancient sailors and Mediterranean legends is as much a part of the experience as the swimming. Families especially love his gentle way with children.",
        image: "https://readdy.ai/api/search-image?query=Warm%20Turkish%20man%20in%20his%20late%20fifties%20with%20a%20thick%20graying%20mustache%20and%20kind%20crinkly%20eyes%20wearing%20a%20traditional%20white%20captain%20cap%20and%20a%20simple%20navy%20jacket%20standing%20near%20the%20wooden%20wheel%20of%20a%20classic%20gulet%20golden%20evening%20light%20traditional%20maritime%20character%20editorial%20portrait%20photography&width=400&height=500&seq=crew-captain-osman&orientation=portrait",
      },
      {
        name: "Fatima Demir",
        role: "Chef",
        experience: "14+ years",
        bio: "Fatima learned to cook from her grandmother in a small village near Antalya, and her food tastes like home — if home happened to be a paradise of olive oil, fresh herbs, and wood-fired everything. Her slow-cooked lamb stew, stuffed vine leaves, and freshly baked gözleme on deck have guests asking for recipes on every charter.",
        image: "https://readdy.ai/api/search-image?query=Warm%20smiling%20Turkish%20woman%20in%20her%20mid%20forties%20with%20dark%20hair%20partially%20covered%20by%20a%20colorful%20headscarf%20wearing%20a%20simple%20white%20apron%20standing%20in%20a%20rustic%20boat%20galley%20with%20clay%20pots%20and%20fresh%20herbs%20around%20her%20soft%20natural%20light%20genuine%20nurturing%20expression%20lifestyle%20portrait%20photography&width=400&height=500&seq=crew-chef-fatima&orientation=portrait",
      },
    ],
  },
  {
    id: "yacht-007",
    name: "Black Pearl Express",
    company: "Turk Yacht",
    type: "Motor Yacht",
    capacity: 6,
    cabins: 3,
    length: "18m",
    year: 2023,
    pricePerDay: 950,
    currency: "EUR",
    halfDayPrice: 500,
    image: "https://readdy.ai/api/search-image?query=Fast%20sleek%20dark-hulled%20motor%20yacht%20speeding%20across%20sparkling%20turquoise%20Mediterranean%20water%20white%20wake%20trail%20aerial%20drone%20perspective%20rugged%20coastline%20and%20mountains%20in%20distance%20thrilling%20luxury%20experience%20editorial%20yachting%20photography%20dynamic%20composition&width=900&height=675&seq=yacht-motor-007&orientation=landscape",
    description: "For those who prefer to travel fast and in style, the Black Pearl Express hits 32 knots while keeping things impossibly smooth. Three double cabins, a retractable sunroof over the cockpit, and a swim platform that doubles as a beach club. Perfect for half-day thrill rides or reaching distant coves before the crowds arrive.",
    amenities: ["Air Conditioning", "WiFi", "Snorkeling Gear", "Retractable Sunroof", "Swim Platform", "Sound System", "Sun Deck", "Fishing Equipment"],
    crewIncluded: true,
    skipperRequired: false,
    rating: 4.6,
    reviewCount: 34,
    availableRoutes: ["Alanya Coastline", "High-Speed Adventure", "Alanya to Side", "Sunset Express"],
    featured: false,
    port: "Alanya Marina",
    crew: [
      {
        name: "Captain Selim Arslan",
        role: "Captain",
        experience: "10+ years at sea",
        bio: "Selim cut his teeth racing speedboats along the Bosphorus before transitioning to luxury charters. He treats the Black Pearl like an extension of himself — every throttle adjustment precise, every turn smooth. His playlist game is legendary (expect everything from Turkish jazz to deep house), and he knows exactly where to find dolphins at sunset.",
        image: "https://readdy.ai/api/search-image?query=Young%20energetic%20Turkish%20man%20in%20his%20mid%20thirties%20with%20stylish%20dark%20hair%20and%20a%20trimmed%20beard%20wearing%20black%20sunglasses%20pushed%20up%20on%20his%20head%20and%20a%20crisp%20white%20polo%20shirt%20standing%20confidently%20at%20the%20helm%20of%20a%20sleek%20modern%20motor%20yacht%20bright%20sun%20sparkling%20on%20the%20sea%20behind%20him%20cool%20charismatic%20expression%20professional%20portrait%20photography&width=400&height=500&seq=crew-captain-selim&orientation=portrait",
      },
      {
        name: "Burak Yıldız",
        role: "First Mate & Marine Naturalist",
        experience: "7+ years",
        bio: "Burak studied marine biology at university and brings genuine passion to every trip. His dolphin and sea turtle spotting skills are almost supernatural, and his snorkeling tours come with a running commentary on Mediterranean marine life that's entertaining rather than academic. Also makes a surprisingly good Aperol Spritz.",
        image: "https://readdy.ai/api/search-image?query=Friendly%20Turkish%20man%20in%20his%20late%20twenties%20with%20curly%20brown%20hair%20and%20an%20easygoing%20smile%20wearing%20a%20casual%20light%20blue%20linen%20shirt%20unbuttoned%20at%20the%20collar%20standing%20on%20the%20swim%20platform%20of%20a%20yacht%20with%20crystal%20clear%20turquoise%20water%20behind%20him%20relaxed%20adventurous%20vibe%20lifestyle%20portrait%20photography%20natural%20daylight&width=400&height=500&seq=crew-mate-burak&orientation=portrait",
      },
    ],
  },
  {
    id: "yacht-008",
    name: "Crystal Waters",
    company: "AYA Yachting",
    type: "Catamaran",
    capacity: 12,
    cabins: 6,
    length: "38ft",
    year: 2020,
    pricePerDay: 780,
    currency: "EUR",
    halfDayPrice: 420,
    image: "https://readdy.ai/api/search-image?query=Modern%20luxury%20sailing%20catamaran%20with%20spacious%20deck%20and%20comfortable%20lounge%20seating%20anchored%20in%20pristine%20turquoise%20Mediterranean%20lagoon%20with%20small%20sandy%20beach%20pine%20forest%20shoreline%20bright%20sunny%20day%20crystal%20clear%20water%20visible%20bottom%20lifestyle%20photography%20serene%20atmosphere&width=900&height=675&seq=yacht-cat-008&orientation=landscape",
    description: "Crystal Waters lives up to its name — the glass-bottom viewing panels in the saloon let you watch marine life glide beneath you while anchored in translucent coves. Six cabins, a spacious indoor-outdoor living area, and stability that even the most seasick-prone guests will appreciate. A firm favorite for multi-day charters.",
    amenities: ["Air Conditioning", "WiFi", "Glass-Bottom Panels", "Snorkeling Gear", "Kayaks", "Paddleboards", "Sound System", "Chef Onboard", "BBQ"],
    crewIncluded: true,
    skipperRequired: false,
    rating: 4.8,
    reviewCount: 53,
    availableRoutes: ["Alanya Coastline", "Alanya to Antalya", "Cave Exploration Tour", "3-Day Blue Cruise"],
    featured: false,
    port: "Alanya Marina",
    crew: [
      {
        name: "Captain Lara Fischer",
        role: "Captain",
        experience: "11+ years at sea",
        bio: "German-born Lara discovered sailing during a gap year in Greece and never went home. She earned her Yachtmaster certification in the UK, skippered charters in the Caribbean, and fell in love with the Turkish coast during a delivery voyage six years ago. Her calm, methodical approach puts even nervous first-timers at ease, and her catamaran handling in tight anchorages is poetry.",
        image: "https://readdy.ai/api/search-image?query=Blonde%20German%20woman%20in%20her%20late%20thirties%20with%20sun-lightened%20hair%20and%20athletic%20build%20wearing%20a%20white%20technical%20sailing%20jacket%20standing%20at%20the%20helm%20station%20of%20a%20modern%20catamaran%20bright%20Mediterranean%20sky%20and%20sea%20around%20her%20focused%20competent%20expression%20professional%20maritime%20portrait%20photography%20natural%20lighting&width=400&height=500&seq=crew-captain-lara&orientation=portrait",
      },
      {
        name: "Diego Santos",
        role: "Chef",
        experience: "12+ years",
        bio: "Diego grew up in Valencia, where paella is practically a religion. His open-flame seafood paella cooked on the aft deck at sunset has become the stuff of legend among repeat guests. He also bakes fresh bread every morning — the smell alone is worth waking up for. Fluent in Spanish, English, and working on his Turkish.",
        image: "https://readdy.ai/api/search-image?query=Spanish%20man%20in%20his%20early%20forties%20with%20dark%20curly%20hair%20and%20warm%20brown%20eyes%20wearing%20a%20casual%20white%20chef%20coat%20with%20rolled-up%20sleeves%20standing%20on%20a%20boat%20deck%20near%20a%20barbecue%20grill%20with%20fresh%20seafood%20arranged%20beside%20him%20bright%20blue%20sky%20and%20sea%20background%20genuine%20happy%20smile%20lifestyle%20portrait%20photography&width=400&height=500&seq=crew-chef-diego&orientation=portrait",
      },
    ],
  },
  {
    id: "yacht-009",
    name: "Liberté",
    company: "Goolets Cruising",
    type: "Sailing Yacht",
    capacity: 4,
    cabins: 2,
    length: "40ft",
    year: 2021,
    pricePerDay: 520,
    currency: "EUR",
    halfDayPrice: 290,
    image: "https://readdy.ai/api/search-image?query=Beautiful%20classic%20sailing%20yacht%20with%20cream%20sails%20and%20teak%20deck%20heeled%20gently%20in%20fresh%20breeze%20deep%20blue%20Mediterranean%20sea%20white%20wake%20sunlight%20sparkling%20on%20water%20romantic%20intimate%20atmosphere%20perfect%20for%20couples%20editorial%20sailing%20photography%20timeless%20elegance&width=900&height=675&seq=yacht-sail-009&orientation=landscape",
    description: "Liberté is the intimate choice for couples seeking a romantic escape on the water. Two beautifully appointed cabins, a cozy teak cockpit, and a curated wine selection come standard. Sail into the sunset with just you, your partner, the skipper, and the endless blue. Champagne on arrival and a gourmet dinner at anchor complete the experience.",
    amenities: ["Autopilot", "Snorkeling Gear", "Sound System", "Cockpit Dining", "Wine Selection", "Champagne Service", "Sun Deck", "Dinghy"],
    crewIncluded: false,
    skipperRequired: true,
    rating: 4.9,
    reviewCount: 41,
    availableRoutes: ["Sunset Sailing", "Romantic Getaway", "Alanya Coastline", "Private Cove Experience"],
    featured: false,
    port: "Alanya Marina",
    crew: [
      {
        name: "Captain Pierre Dubois",
        role: "Skipper",
        experience: "16+ years at sea",
        bio: "Pierre left a corporate career in Paris to chase the horizon, and it shows in the way he sails — with joy, not just skill. He's skippered honeymoon charters, anniversary surprises, and more proposals than he can count, and his instinct for creating romantic moments (the perfect sunset spot, a surprise champagne toast, a secluded cove for two) is unmatched. He'll discreetly vanish when you want privacy and reappear exactly when you need a fresh drink.",
        image: "https://readdy.ai/api/search-image?query=Charming%20French%20man%20in%20his%20mid%20forties%20with%20salt%20and%20pepper%20stubble%20and%20windswept%20light%20brown%20hair%20wearing%20a%20relaxed%20navy%20blue%20Breton%20striped%20shirt%20standing%20at%20the%20tiller%20of%20a%20classic%20sailing%20yacht%20golden%20sunset%20reflecting%20on%20the%20water%20behind%20him%20warm%20romantic%20smile%20lifestyle%20portrait%20photography%20natural%20light&width=400&height=500&seq=crew-captain-pierre&orientation=portrait",
      },
    ],
  },
  {
    id: "yacht-010",
    name: "Dolphin's Dance",
    company: "Era Yachting",
    type: "Gulet",
    capacity: 8,
    cabins: 4,
    length: "22m",
    year: 2020,
    pricePerDay: 580,
    currency: "EUR",
    halfDayPrice: 320,
    image: "https://readdy.ai/api/search-image?query=Compact%20traditional%20Turkish%20wooden%20gulet%20with%20cream%20sails%20and%20polished%20teak%20deck%20cruising%20along%20rugged%20Mediterranean%20coastline%20bright%20blue%20sky%20puffy%20white%20clouds%20dolphins%20leaping%20in%20bow%20wake%20crystal%20clear%20turquoise%20water%20joyful%20atmosphere%20editorial%20travel%20photography%20vibrant%20colors&width=900&height=675&seq=yacht-gulet-010&orientation=landscape",
    description: "Don't let the modest size fool you — Dolphin's Dance is packed with character. This intimate gulet is ideal for small groups and families, with four snug cabins, a shaded dining cockpit, and a bow sunbathing area that doubles as a dolphin-spotting platform. The crew of two knows every hidden cove along the Alanya coast like the back of their hand.",
    amenities: ["Air Conditioning", "WiFi", "Snorkeling Gear", "Fishing Equipment", "Sound System", "Sun Deck", "BBQ", "Canoe"],
    crewIncluded: true,
    skipperRequired: false,
    rating: 4.6,
    reviewCount: 27,
    availableRoutes: ["Alanya Coastline", "Dolphin Spotting Tour", "Alanya to Gazipaşa", "Family Day Out"],
    featured: false,
    port: "Alanya Marina",
    crew: [
      {
        name: "Captain Hakan Özdemir",
        role: "Captain",
        experience: "15+ years at sea",
        bio: "Hakan was born and raised in Alanya — he's been swimming in these waters since he could walk. His local knowledge is encyclopedic: which cove has the best snorkeling at 9am, where the sea turtles feed, which beach has the softest sand for a picnic. He's patient, funny, and treats every charter like he's showing old friends around his hometown.",
        image: "https://readdy.ai/api/search-image?query=Friendly%20Turkish%20man%20in%20his%20mid%20forties%20with%20dark%20hair%20and%20a%20well-kept%20short%20beard%20wearing%20a%20casual%20sky%20blue%20polo%20shirt%20and%20sunglasses%20hanging%20from%20his%20collar%20standing%20on%20the%20bow%20of%20a%20wooden%20gulet%20with%20the%20Alanya%20castle%20promontory%20visible%20in%20the%20distance%20bright%20sunny%20day%20warm%20genuine%20smile%20lifestyle%20maritime%20portrait%20photography&width=400&height=500&seq=crew-captain-hakan&orientation=portrait",
      },
      {
        name: "Zeynep Aksu",
        role: "Chef",
        experience: "9+ years",
        bio: "Zeynep brings the flavours of the Turkish countryside to the sea. She sources eggs, cheese, honey, and vegetables from farms near her family's village in the Taurus foothills, and every meal tells a story. Her breakfast spreads — think menemen, freshly baked simit, local honey, and figs still warm from the sun — are worth the charter price alone.",
        image: "https://readdy.ai/api/search-image?query=Turkish%20woman%20in%20her%20mid%20thirties%20with%20warm%20brown%20eyes%20and%20dark%20hair%20pulled%20back%20in%20a%20loose%20ponytail%20wearing%20a%20simple%20white%20apron%20over%20a%20colorful%20patterned%20blouse%20standing%20in%20a%20compact%20boat%20kitchen%20arranging%20a%20beautiful%20Turkish%20breakfast%20spread%20with%20fresh%20bread%20honey%20and%20olives%20soft%20morning%20light%20genuine%20nurturing%20smile%20lifestyle%20portrait%20photography&width=400&height=500&seq=crew-chef-zeynep&orientation=portrait",
      },
    ],
  },
  {
    id: "yacht-011",
    name: "Neptün",
    company: "Alanya Mavi Yachting",
    type: "Motor Yacht",
    capacity: 10,
    cabins: 4,
    length: "25m",
    year: 2022,
    pricePerDay: 1400,
    currency: "EUR",
    halfDayPrice: 750,
    image: "https://readdy.ai/api/search-image?query=Premium%20modern%20motor%20yacht%20with%20sleek%20silver%20hull%20and%20large%20panoramic%20windows%20cruising%20past%20dramatic%20Alanya%20castle%20promontory%20bright%20sunny%20afternoon%20turquoise%20Mediterranean%20sea%20spacious%20flybridge%20with%20lounge%20seating%20luxury%20lifestyle%20photography%20high%20detail%20professional%20quality&width=900&height=675&seq=yacht-motor-011&orientation=landscape",
    description: "Neptün is Alanya Mavi Yachting's flagship motor yacht — a 25-meter powerhouse with a top speed of 30 knots and a ride so smooth you will forget you are on water. Four double cabins with en-suites, a vast flybridge with wet bar, and underwater lights that turn the sea into a glowing turquoise spectacle after dark. The crew of four delivers flawless five-star service.",
    amenities: ["Air Conditioning", "WiFi", "Jet Ski", "Snorkeling Gear", "Flybridge Wet Bar", "Swim Platform", "Sound System", "Underwater Lights", "Satellite TV", "Tender Boat"],
    crewIncluded: true,
    skipperRequired: false,
    rating: 4.8,
    reviewCount: 19,
    availableRoutes: ["Alanya Coastline", "Alanya to Antalya", "Alanya to Side", "Full Moon Cruise"],
    featured: true,
    port: "Alanya Marina",
    crew: [
      {
        name: "Captain Arda Tekin",
        role: "Captain",
        experience: "18+ years at sea",
        bio: "Arda spent a decade commanding commercial vessels through the Bosphorus — one of the world's busiest and trickiest waterways — so handling a luxury motor yacht on the open Mediterranean is, in his words, 'a holiday.' His calm command of the bridge and dry sense of humor make guests feel instantly at ease. Ask him about the time he navigated through a Force 8 storm off the Greek islands.",
        image: "https://readdy.ai/api/search-image?query=Distinguished%20Turkish%20man%20in%20his%20early%20fifties%20with%20silver-streaked%20dark%20hair%20and%20a%20neatly%20trimmed%20beard%20wearing%20a%20crisp%20dark%20navy%20captain%20uniform%20standing%20with%20arms%20crossed%20on%20the%20bridge%20of%20a%20sleek%20modern%20motor%20yacht%20panoramic%20sea%20view%20through%20windows%20behind%20him%20authoritative%20composed%20expression%20professional%20maritime%20portrait%20photography&width=400&height=500&seq=crew-captain-arda&orientation=portrait",
      },
      {
        name: "Sofia Papadopoulos",
        role: "Chef",
        experience: "13+ years",
        bio: "Sofia grew up between Athens and Istanbul and her cooking reflects both worlds — think Greek meze meets Turkish meyhane. Her octopus stifado is the dish guests email about months later, and her baklava recipe comes from her Istanbul grandmother. She also runs a popular food blog in the off-season, so expect every plate to be camera-ready.",
        image: "https://readdy.ai/api/search-image?query=Greek%20woman%20in%20her%20late%20thirties%20with%20olive%20skin%20and%20dark%20wavy%20hair%20pulled%20into%20a%20stylish%20low%20bun%20wearing%20a%20fitted%20white%20chef%20coat%20standing%20in%20a%20bright%20modern%20yacht%20galley%20holding%20a%20platter%20of%20colorful%20Mediterranean%20dishes%20soft%20daylight%20streaming%20in%20warm%20confident%20smile%20culinary%20professional%20portrait%20photography&width=400&height=500&seq=crew-chef-sofia&orientation=portrait",
      },
      {
        name: "Elif Nur",
        role: "Stewardess",
        experience: "6+ years",
        bio: "Elif trained in luxury hotel management in Antalya before bringing her skills to the water. Her cocktail game is exceptional — her signature 'Neptün Spritz' (secret recipe, no amount of asking will get it out of her) is the most-requested drink in the fleet. She's also a certified yoga instructor and leads optional sunrise sessions on the flybridge.",
        image: "https://readdy.ai/api/search-image?query=Young%20Turkish%20woman%20in%20her%20late%20twenties%20with%20long%20dark%20hair%20and%20bright%20engaging%20eyes%20wearing%20a%20crisp%20white%20short-sleeve%20uniform%20shirt%20standing%20on%20the%20deck%20of%20a%20luxury%20motor%20yacht%20holding%20a%20tray%20with%20colorful%20cocktails%20Mediterranean%20sea%20and%20blue%20sky%20behind%20her%20friendly%20professional%20smile%20service%20portrait%20photography%20natural%20daylight&width=400&height=500&seq=crew-stewardess-elif&orientation=portrait",
      },
    ],
  },
  {
    id: "yacht-012",
    name: "Zephyr",
    company: "Sirena Yachting Alanya",
    type: "Catamaran",
    capacity: 20,
    cabins: 10,
    length: "50ft",
    year: 2023,
    pricePerDay: 1600,
    currency: "EUR",
    halfDayPrice: 850,
    image: "https://readdy.ai/api/search-image?query=Massive%20modern%20luxury%20catamaran%20with%20twin%20white%20hulls%20expansive%20deck%20with%20sun%20loungers%20and%20shaded%20lounge%20area%20anchored%20off%20pristine%20Mediterranean%20beach%20pine%20trees%20framing%20turquoise%20water%20sunny%20summer%20day%20group%20celebration%20atmosphere%20editorial%20yachting%20photography%20wide%20angle%20vibrant&width=900&height=675&seq=yacht-cat-012&orientation=landscape",
    description: "Zephyr is the largest catamaran in the Alanya charter fleet and the go-to choice for big celebrations. Ten cabins sleep up to 20 guests comfortably — think wedding after-parties, milestone birthdays, and corporate retreats. The 50-square-meter flybridge is essentially a floating rooftop bar, and the hydraulic swim platform doubles as a launch pad for the fleet of water toys.",
    amenities: ["Air Conditioning", "WiFi", "Jet Ski", "Snorkeling Gear", "Kayaks", "Paddleboards", "Chef Onboard", "Flybridge Bar", "BBQ", "Ice Maker", "Sound System", "Water Slide"],
    crewIncluded: true,
    skipperRequired: false,
    rating: 4.7,
    reviewCount: 22,
    availableRoutes: ["Alanya Coastline", "Alanya to Antalya", "Island Hopping", "Event Charter"],
    featured: true,
    port: "Alanya Marina",
    crew: [
      {
        name: "Captain Marco Venturi",
        role: "Captain",
        experience: "17+ years at sea",
        bio: "Marco grew up on the Italian Riviera and has captained catamarans from the Seychelles to the British Virgin Islands. He chose Alanya as his home port for the reliable winds and the quality of the sailing community. Running a 50-foot catamaran with 20 guests takes serious skill, and Marco does it with the relaxed confidence of someone who's seen it all. His karaoke performances at the flybridge bar are, reportedly, something to behold.",
        image: "https://readdy.ai/api/search-image?query=Charismatic%20Italian%20man%20in%20his%20mid%20forties%20with%20tanned%20skin%20and%20sun-bleached%20brown%20hair%20wearing%20a%20casual%20white%20linen%20shirt%20unbuttoned%20at%20the%20collar%20and%20sunglasses%20resting%20on%20his%20head%20standing%20at%20the%20helm%20of%20a%20large%20catamaran%20bright%20Mediterranean%20sea%20stretching%20behind%20him%20confident%20relaxed%20smile%20lifestyle%20maritime%20portrait%20photography%20golden%20hour&width=400&height=500&seq=crew-captain-marco&orientation=portrait",
      },
      {
        name: "Lucia Ferrara",
        role: "Chef",
        experience: "11+ years",
        bio: "Sicilian-born Lucia specializes in feeding crowds without ever making it feel like mass catering. Her multi-course group dinners — antipasti, handmade pasta, grilled catch of the day, cannoli — feel like a wedding feast in the best possible way. She once catered a 20-person birthday dinner entirely from the yacht's galley and received a standing ovation.",
        image: "https://readdy.ai/api/search-image?query=Sicilian%20woman%20in%20her%20late%20thirties%20with%20dark%20curly%20hair%20tied%20up%20in%20a%20colorful%20scarf%20wearing%20a%20white%20chef%20apron%20over%20a%20bright%20sundress%20standing%20on%20a%20spacious%20catamaran%20deck%20beside%20a%20table%20laden%20with%20a%20Mediterranean%20feast%20of%20pasta%20seafood%20and%20fresh%20fruit%20bright%20sunny%20day%20warm%20joyful%20smile%20culinary%20lifestyle%20portrait%20photography&width=400&height=500&seq=crew-chef-lucia&orientation=portrait",
      },
      {
        name: "Ali Koç",
        role: "Deckhand & Water Sports Instructor",
        experience: "5+ years",
        bio: "Ali is the human embodiment of fun — if there's a water toy on board, he's probably already in the water demonstrating it. A certified PADI dive instructor and former competitive swimmer, he runs snorkeling tours, paddleboard races, and jet ski sessions with infectious enthusiasm. Kids absolutely adore him, and he somehow remembers every single name on a 20-person charter.",
        image: "https://readdy.ai/api/search-image?query=Young%20athletic%20Turkish%20man%20in%20his%20mid%20twenties%20with%20short%20dark%20hair%20and%20a%20tanned%20toned%20physique%20wearing%20board%20shorts%20and%20a%20sleeveless%20rash%20guard%20standing%20on%20the%20swim%20platform%20of%20a%20catamaran%20holding%20a%20paddleboard%20bright%20turquoise%20water%20splashing%20around%20him%20huge%20energetic%20smile%20adventurous%20lifestyle%20portrait%20photography%20summer%20vibes&width=400&height=500&seq=crew-deckhand-ali&orientation=portrait",
      },
    ],
  },
  {
    id: "yacht-013",
    name: "Meltemi",
    company: "Vela Mare Alanya",
    type: "Sailing Yacht",
    capacity: 8,
    cabins: 4,
    length: "50ft",
    year: 2022,
    pricePerDay: 780,
    currency: "EUR",
    halfDayPrice: 420,
    image: "https://readdy.ai/api/search-image?query=Performance%20cruising%20sailing%20yacht%20with%20full%20sails%20catching%20strong%20afternoon%20breeze%20deep%20blue%20Mediterranean%20sea%20whitecaps%20sparkling%20in%20sunlight%20mountainous%20coastline%20distant%20horizon%20exhilarating%20sailing%20experience%20professional%20crew%20visible%20editorial%20photography%20crisp%20sharp%20composition&width=900&height=675&seq=yacht-sail-013&orientation=landscape",
    description: "Named after the famous Aegean summer wind, Meltemi is built for sailors who want to feel the power of the sea. This 50-foot performance cruiser boasts a towering mast and a deep keel that carves through swells like a blade. Four comfortable cabins, a well-stocked galley, and a cockpit designed for spirited conversation under the stars. Ideal for active groups who want to earn their sunset cocktails.",
    amenities: ["Autopilot", "Snorkeling Gear", "Fishing Equipment", "Sound System", "Cockpit Dining", "Sun Deck", "Chart Plotter", "Dinghy", "SUP Board"],
    crewIncluded: false,
    skipperRequired: true,
    rating: 4.9,
    reviewCount: 31,
    availableRoutes: ["Alanya Coastline", "Wind-Seeker's Route", "Alanya to Antalya", "2-Day Sailing Adventure"],
    featured: false,
    port: "Alanya Marina",
    crew: [
      {
        name: "Captain Jens Müller",
        role: "Skipper",
        experience: "19+ years at sea",
        bio: "Jens is a former offshore racing sailor from Hamburg who traded the North Sea's grey chop for the Turkish Riviera's turquoise swells and never looked back. He's skippered in three Fastnet races and still brings that same precision and competitive edge to every charter — except now he's happy to let you take the wheel. If you want to learn serious sailing technique, there's no better teacher on the coast.",
        image: "https://readdy.ai/api/search-image?query=Tall%20athletic%20German%20man%20in%20his%20late%20forties%20with%20short%20salt%20and%20pepper%20hair%20and%20a%20weather-beaten%20face%20wearing%20a%20technical%20sailing%20jacket%20with%20reflective%20details%20standing%20at%20the%20winch%20of%20a%20performance%20sailing%20yacht%20strong%20wind%20tousling%20his%20hair%20intense%20focused%20blue%20eyes%20looking%20at%20the%20horizon%20professional%20maritime%20portrait%20photography%20dramatic%20sky&width=400&height=500&seq=crew-captain-jens&orientation=portrait",
      },
    ],
  },
  {
    id: "yacht-014",
    name: "Empress Azure",
    company: "Mare Nostrum Charters",
    type: "Luxury Yacht",
    capacity: 8,
    cabins: 4,
    length: "30m",
    year: 2023,
    pricePerDay: 3500,
    currency: "EUR",
    halfDayPrice: 1900,
    image: "https://readdy.ai/api/search-image?query=Stunning%20super%20yacht%20with%20gleaming%20white%20hull%20and%20floor-to-ceiling%20tinted%20glass%20panels%20moored%20in%20exclusive%20marina%20Mediterranean%20evening%20golden%20lights%20reflecting%20on%20calm%20water%20elegant%20outdoor%20dining%20setup%20on%20aft%20deck%20sophisticated%20atmosphere%20ultra%20luxury%20lifestyle%20editorial%20photography%20premium%20composition&width=900&height=675&seq=yacht-luxury-014&orientation=landscape",
    description: "Empress Azure is the newest jewel in the Mare Nostrum fleet — a 30-meter masterpiece from an acclaimed Dutch shipyard. Four palatial suites, each with a private balcony, a beach club that opens directly to the sea, and a bow Jacuzzi with 360-degree views. The onboard chef trained at a Michelin-starred restaurant in Istanbul. For those who demand nothing less than perfection.",
    amenities: ["Jacuzzi", "Beach Club", "Private Balconies", "Air Conditioning", "WiFi", "Jet Ski", "Snorkeling Gear", "Chef Onboard", "Butler Service", "Wine Cellar", "Cinema Room", "Tender Boat"],
    crewIncluded: true,
    skipperRequired: false,
    rating: 5.0,
    reviewCount: 12,
    availableRoutes: ["Alanya to Antalya", "Alanya to Cyprus", "Turkish Riviera Grand Tour", "Bespoke Custom Route"],
    featured: true,
    port: "Alanya Marina",
    crew: [
      {
        name: "Captain Dimitri Antonov",
        role: "Captain",
        experience: "22+ years at sea",
        bio: "Dimitri graduated from the Maritime Academy of Odessa with distinction and has commanded vessels from the Black Sea to the South Pacific. His logbook includes two Atlantic crossings, a circumnavigation of the Mediterranean, and more 5-star charters than he bothers counting. Guests describe him as the perfect blend of old-school professionalism and genuine warmth — formal when it matters, cracking jokes at the crew dinner.",
        image: "https://readdy.ai/api/search-image?query=Eastern%20European%20man%20in%20his%20early%20fifties%20with%20distinguished%20silver%20hair%20combed%20back%20and%20a%20neatly%20trimmed%20goatee%20wearing%20an%20immaculate%20white%20captain%20uniform%20with%20gold%20stripes%20standing%20on%20the%20bridge%20wing%20of%20a%20superyacht%20overlooking%20a%20marina%20at%20golden%20hour%20commanding%20yet%20warm%20expression%20premium%20maritime%20portrait%20photography&width=400&height=500&seq=crew-captain-dimitri&orientation=portrait",
      },
      {
        name: "Amélie Laurent",
        role: "Chef",
        experience: "16+ years in haute cuisine",
        bio: "Paris-trained Amélie spent eight years in Michelin-starred kitchens (including two years under a three-star chef in Lyon) before answering the call of the sea. Her tasting menus are culinary theatre — seven courses, each paired with wines from the yacht's cellar, each plate a work of art. She sources caviar from the Caspian, truffles from Alba, and fish from the boat's own morning catch.",
        image: "https://readdy.ai/api/search-image?query=Elegant%20French%20woman%20in%20her%20early%20forties%20with%20porcelain%20skin%20and%20dark%20hair%20pulled%20into%20a%20flawless%20low%20bun%20wearing%20a%20tailored%20white%20chef%20jacket%20with%20subtle%20grey%20trim%20standing%20in%20a%20state-of-the-art%20galley%20kitchen%20on%20a%20luxury%20yacht%20holding%20a%20beautifully%20plated%20gourmet%20dish%20poised%20artistic%20expression%20culinary%20professional%20portrait%20photography&width=400&height=500&seq=crew-chef-amelie&orientation=portrait",
      },
      {
        name: "James Whitfield",
        role: "Chief Steward",
        experience: "10+ years",
        bio: "British-born James trained as a butler in the English countryside before discovering that superyachts offered a far more interesting workplace. His service is so discreet you'll forget he's there — until your glass is mysteriously refilled, the towels have been changed, and the deck cushions are somehow always in the perfect spot. He knows more about wine than most sommeliers and tells a cracking good story after dinner.",
        image: "https://readdy.ai/api/search-image?query=Distinguished%20British%20man%20in%20his%20late%20thirties%20with%20short%20neatly%20styled%20light%20brown%20hair%20wearing%20a%20crisp%20white%20steward%20uniform%20with%20black%20bow%20tie%20and%20polished%20silver%20name%20badge%20standing%20on%20the%20aft%20deck%20of%20a%20luxury%20yacht%20at%20sunset%20holding%20a%20wine%20decanter%20composed%20professional%20smile%20premium%20service%20portrait%20photography&width=400&height=500&seq=crew-steward-james&orientation=portrait",
      },
    ],
  },
  {
    id: "yacht-015",
    name: "Sultan's Pearl",
    company: "Cleopatra Yachting Alanya",
    type: "Luxury Yacht",
    capacity: 12,
    cabins: 6,
    length: "38m",
    year: 2024,
    pricePerDay: 4200,
    currency: "EUR",
    halfDayPrice: 2200,
    image: "https://readdy.ai/api/search-image?query=Magnificent%20three-deck%20super%20yacht%20with%20elegant%20navy%20blue%20hull%20and%20gold%20trim%20accents%20anchored%20at%20golden%20sunset%20off%20Alanya%20coast%20castle%20silhouette%20in%20background%20infinity%20pool%20on%20main%20deck%20helicopter%20landing%20pad%20ultimate%20luxury%20lifestyle%20editorial%20yachting%20photography%20breathtaking%20scene%20premium%20cinematic&width=900&height=675&seq=yacht-luxury-015&orientation=landscape",
    description: "There is luxury, and then there is Sultan's Pearl. This 38-meter superyacht is the undisputed flagship of Cleopatra Yachting and one of the most exclusive charters on the entire Turkish Riviera. Six sumptuous staterooms named after Ottoman sultanas, a glass-walled infinity pool on the main deck, a private cinema, a fully equipped gym with sea views, and a helipad for those who prefer to arrive by air. A crew of seven, including a private chef and a dedicated concierge, ensures that every desire — no matter how extravagant — is fulfilled before you even think to ask.",
    amenities: ["Infinity Pool", "Helipad", "Cinema Room", "Gym", "Jacuzzi", "Air Conditioning", "WiFi", "Jet Ski", "Seabob", "Snorkeling Gear", "Chef Onboard", "Butler Service", "Wine Cellar", "Tender Boat", "Concierge"],
    crewIncluded: true,
    skipperRequired: false,
    rating: 5.0,
    reviewCount: 8,
    availableRoutes: ["Alanya to Antalya", "Alanya to Cyprus", "Turkish Riviera Grand Tour", "Bespoke Custom Route", "Greek Islands Voyage"],
    featured: true,
    port: "Alanya Marina",
    crew: [
      {
        name: "Captain Murat Karaman",
        role: "Captain",
        experience: "28+ years at sea",
        bio: "Captain Murat is the most experienced captain in the Alanya charter fleet and widely respected across the entire Turkish yachting community. He started as a deckhand on cargo ships at sixteen, earned his master's license by twenty-five, and has commanded superyachts for the past two decades. Heads of state, royalty, and captains of industry have entrusted their voyages to him. When Murat says a route is safe, the conversation ends.",
        image: "https://readdy.ai/api/search-image?query=Distinguished%20Turkish%20man%20in%20his%20early%20sixties%20with%20thick%20silver%20hair%20and%20a%20well-groomed%20white%20beard%20wearing%20an%20immaculate%20white%20captain%20uniform%20with%20five%20gold%20stripes%20and%20a%20ceremonial%20cap%20standing%20on%20the%20bridge%20of%20a%20superyacht%20with%20polished%20mahogany%20and%20brass%20details%20commanding%20wise%20presence%20the%20look%20of%20a%20man%20who%20has%20seen%20every%20sea%20premium%20maritime%20portrait%20photography&width=400&height=500&seq=crew-captain-murat&orientation=portrait",
      },
      {
        name: "François Dubois",
        role: "Chef",
        experience: "20+ years in Michelin-starred restaurants",
        bio: "Chef François is the culinary crown jewel of the Turkish Riviera charter scene. He held two Michelin stars at his restaurant in Lyon before a superyacht owner convinced him to bring his artistry to sea. His degustation menus change with the seasons, incorporating Turkish ingredients through a French lens — think İskenderun prawns in beurre blanc, or rose-infused crème brûlée with Antep pistachios. The galley on Sultan's Pearl was custom-designed around his specifications.",
        image: "https://readdy.ai/api/search-image?query=Distinguished%20French%20chef%20in%20his%20early%20fifties%20with%20greying%20temples%20and%20a%20meticulously%20styled%20short%20beard%20wearing%20an%20elegant%20white%20chef%20jacket%20with%20subtle%20blue%20embroidery%20and%20a%20tricolor%20collar%20pin%20standing%20in%20a%20pristine%20gourmet%20galley%20kitchen%20holding%20a%20copper%20pan%20confident%20artistic%20expression%20culinary%20master%20portrait%20photography%20professional%20lighting&width=400&height=500&seq=crew-chef-francois&orientation=portrait",
      },
      {
        name: "Natalia Sokolova",
        role: "Chief Stewardess",
        experience: "14+ years in luxury hospitality",
        bio: "Natalia managed VIP services at five-star hotels in Moscow and Dubai before moving to superyachts, where she found her true calling. She coordinates the crew of seven with military precision and the warmth of a favourite aunt. Whether arranging a helicopter transfer, sourcing a rare vintage, or organizing a surprise birthday dinner on a secluded beach, her response is always the same: 'Consider it done.'",
        image: "https://readdy.ai/api/search-image?query=Elegant%20Russian%20woman%20in%20her%20early%20forties%20with%20sleek%20blonde%20hair%20in%20a%20sophisticated%20updo%20wearing%20a%20tailored%20white%20stewardess%20uniform%20with%20gold%20buttons%20standing%20in%20an%20elegant%20superyacht%20salon%20with%20fresh%20flower%20arrangements%20around%20her%20composed%20professional%20smile%20warm%20yet%20refined%20presence%20luxury%20service%20portrait%20photography&width=400&height=500&seq=crew-stewardess-natalia&orientation=portrait",
      },
    ],
  },
];