#!/usr/bin/env bash
#
# Alanya Holidays — VPS Deployment Interactive Wizard
# Generated by /wizard skill.
#

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=5
TOTAL_MINUTES=10

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env.production}"
WRITTEN_ENV=()
SKIPPED=()

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  This wizard guides you through deploying Alanya Holidays to your Hostinger VPS.\n' "$DIM"
  printf '  It captures IP and SSH info, checks DNS, installs Docker on the server, and runs\n'
  printf '  the production containers with SSL certificate generation.%s\n\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current: %s]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$current" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Deployment wizard finished!%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} )) && note "saved credentials to $ENV_FILE: ${WRITTEN_ENV[*]}"
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

banner "Alanya Holidays — VPS Deployment Wizard"

# Stage 1: VPS Access Credentials
stage "VPS Credentials & Connection" 2
say "Enter your Hostinger VPS IP address and SSH credentials."
open_url "https://hpanel.hostinger.com/vps"
step "Copy the public IPv4 address of your VPS from Hostinger hPanel."
ask VPS_IP "Enter VPS IP address:"
ask VPS_USER "Enter SSH username (default: root):"
VPS_USER="${VPS_USER:-root}"

write_env "VPS_IP" "$VPS_IP"
write_env "VPS_USER" "$VPS_USER"

say "Testing SSH connection to $VPS_USER@$VPS_IP..."
if ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 "$VPS_USER@$VPS_IP" "echo 'SSH connection successful!'" 2>/dev/null; then
  printf '  %s✓ Connected to VPS via SSH!%s\n' "$GREEN" "$RESET"
else
  warn "Could not connect automatically via passwordless SSH."
  say "Make sure your SSH public key is added to VPS (~/.ssh/authorized_keys) or run:"
  say "  ssh-copy-id $VPS_USER@$VPS_IP"
fi
pause "Press Enter once SSH connection is verified..."

# Stage 2: DNS Configuration
stage "Domain DNS Configuration" 2
say "Ensure alanyaholidays.com points to your VPS IP: $VPS_IP"
open_url "https://hpanel.hostinger.com/dns"
step "In Hostinger hPanel -> DNS Zone Editor (or Cloudflare):"
step "Set A record for '@' -> $VPS_IP"
step "Set A record for 'www' -> $VPS_IP"
pause "Press Enter after updating DNS records..."

# Stage 3: VPS Server Provisioning
stage "VPS Host Provisioning (Docker, Swap, Firewall)" 2
say "We will prepare the remote VPS host with required dependencies."
if confirm "Run remote provisioning on $VPS_USER@$VPS_IP via SSH?"; then
  say "Executing setup script on remote VPS..."
  ssh "$VPS_USER@$VPS_IP" bash -s <<'EOF'
    set -e
    echo "=== 1. Setting up 2GB Swap ==="
    if [ ! -f /swapfile ]; then
      fallocate -l 2G /swapfile || dd if=/dev/zero of=/swapfile bs=1M count=2048
      chmod 600 /swapfile
      mkswap /swapfile
      swapon /swapfile
      echo '/swapfile none swap sw 0 0' >> /etc/fstab
      sysctl vm.swappiness=20
      echo 'vm.swappiness=20' >> /etc/sysctl.conf
      echo "Swap configured successfully."
    else
      echo "Swapfile already exists."
    fi

    echo "=== 2. Configuring Firewall (UFW) ==="
    if command -v ufw >/dev/null 2>&1; then
      ufw default deny incoming || true
      ufw default allow outgoing || true
      ufw allow 22/tcp || true
      ufw allow 80/tcp || true
      ufw allow 443/tcp || true
      ufw --force enable || true
    fi

    echo "=== 3. Checking Docker & Docker Compose ==="
    if ! command -v docker >/dev/null 2>&1; then
      echo "Installing Docker..."
      curl -fsSL https://get.docker.com | sh
    fi
    echo "VPS provisioning complete!"
EOF
  printf '  %s✓ Remote VPS provisioning completed!%s\n' "$GREEN" "$RESET"
else
  warn "Skipped automatic remote provisioning."
fi
pause

# Stage 4: Code Sync & Container Launch
stage "Deploying Production Containers" 3
say "Syncing repository files and starting production Docker containers."
if confirm "Deploy application stack to $VPS_USER@$VPS_IP?"; then
  say "Rsyncing workspace files to /var/www/alanya-holidays on VPS..."
  ssh "$VPS_USER@$VPS_IP" "mkdir -p /var/www/alanya-holidays"
  rsync -avz --exclude '.git' --exclude 'node_modules' --exclude 'dist' ./ "$VPS_USER@$VPS_IP:/var/www/alanya-holidays/"

  say "Starting Docker Compose on remote VPS..."
  ssh "$VPS_USER@$VPS_IP" bash -s <<'EOF'
    cd /var/www/alanya-holidays
    if ! docker compose -f docker-compose.prod.yml up -d --build; then
      echo "=== BACKEND LOGS ==="
      docker compose -f docker-compose.prod.yml logs --tail=50 backend
      exit 1
    fi
    echo "Docker containers launched successfully."
EOF
  printf '  %s✓ Application containers launched on VPS!%s\n' "$GREEN" "$RESET"
else
  warn "Skipped container deployment."
fi
pause

# Stage 5: SSL & Final Healthcheck
stage "SSL Setup & Health Verification" 1
say "Issuing Let's Encrypt SSL certificate and checking site health."
ask DOMAIN_EMAIL "Enter admin email for SSL cert (e.g. admin@alanyaholidays.com):"

if confirm "Issue Let's Encrypt SSL certificate now?"; then
  ssh "$VPS_USER@$VPS_IP" bash -s <<EOF
    set -e
    cd /var/www/alanya-holidays
    chmod +x ./scripts/init-letsencrypt.sh
    ./scripts/init-letsencrypt.sh alanyaholidays.com ${DOMAIN_EMAIL:-admin@alanyaholidays.com}
EOF
  printf '  %s✓ SSL Certificate configured!%s\n' "$GREEN" "$RESET"
fi

say "Checking HTTP status..."
if curl -sI "http://$VPS_IP" | grep -E "(HTTP/|Server:)"; then
  printf '  %s✓ Nginx responds successfully on http://%s!%s\n' "$GREEN" "$VPS_IP" "$RESET"
else
  warn "Could not reach HTTP service on $VPS_IP."
fi

finish
