-- Migration: 20260818000000_concierge_enquiries
-- Purpose: Add concierge_enquiries table for holiday concierge, personal shopper, and admin management

CREATE TABLE IF NOT EXISTS public.concierge_enquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    subject TEXT,
    message TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'responded', 'archived')),
    enquiry_type TEXT NOT NULL DEFAULT 'general',
    assigned_to UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    service_type TEXT,
    dates TEXT,
    duration TEXT,
    party_size INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_concierge_enquiries_created_at
    ON public.concierge_enquiries (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_concierge_enquiries_status
    ON public.concierge_enquiries (status);

-- Enable RLS
ALTER TABLE public.concierge_enquiries ENABLE ROW LEVEL SECURITY;

-- 1. Anyone (including unauthenticated guests) can submit an enquiry
CREATE POLICY "concierge_enquiries_public_insert" ON public.concierge_enquiries
    FOR INSERT
    WITH CHECK (true);

-- 2. Public read for anonymized recent enquiries sidebar feed
CREATE POLICY "concierge_enquiries_public_select" ON public.concierge_enquiries
    FOR SELECT
    USING (true);

-- 3. Admin full access for managing and updating enquiries
CREATE POLICY "concierge_enquiries_admin_all" ON public.concierge_enquiries
    FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = (SELECT auth.uid())
            AND profiles.role = 'admin'
        )
    );
