-- Migration: 20260822000002_email_outbox
-- Purpose: Durable email delivery (audit 2.4). Emails are enqueued in the DB
-- and delivered by the process-email-outbox edge function driven by pg_cron.
-- Replaces fire-and-forget send-email invocations that silently lost mail on restart.

CREATE TABLE IF NOT EXISTS public.email_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payload JSONB NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'failed')),
    attempts INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    sent_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_email_outbox_pending
    ON public.email_outbox (created_at)
    WHERE status = 'pending';

ALTER TABLE public.email_outbox ENABLE ROW LEVEL SECURITY;

-- No policies: only service role (backend + edge functions) touches the outbox.

-- Enqueue: called by the backend within/near business operations.
CREATE OR REPLACE FUNCTION public.enqueue_email(
    p_payload JSONB
) RETURNS BIGINT AS $$
DECLARE
    v_id BIGINT;
BEGIN
    IF p_payload->>'type' IS NULL THEN
        RAISE EXCEPTION 'email payload must contain a "type"';
    END IF;

    INSERT INTO public.email_outbox (payload)
    VALUES (p_payload)
    RETURNING id INTO v_id;

    RETURN v_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE ALL ON FUNCTION public.enqueue_email FROM anon, public;

-- Claim a batch of pending emails for delivery (concurrency-safe).
-- Marks claimed rows as 'sent' is done by deliver step; here we return rows.
CREATE OR REPLACE FUNCTION public.claim_pending_emails(
    p_batch_size INTEGER DEFAULT 20
) RETURNS TABLE (
    id BIGINT,
    payload JSONB,
    attempts INTEGER
) AS $$
DECLARE
    v_now TIMESTAMPTZ := NOW();
BEGIN
    RETURN QUERY
    UPDATE public.email_outbox
    SET attempts = attempts + 1
    WHERE id IN (
        SELECT id FROM public.email_outbox
        WHERE status = 'pending'
          AND attempts < 5
        ORDER BY created_at
        LIMIT GREATEST(p_batch_size, 1)
        FOR UPDATE SKIP LOCKED
    )
    RETURNING email_outbox.id, email_outbox.payload, email_outbox.attempts;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE ALL ON FUNCTION public.claim_pending_emails FROM anon, public;

-- Mark delivery result.
CREATE OR REPLACE FUNCTION public.complete_email_delivery(
    p_id BIGINT,
    p_success BOOLEAN,
    p_error TEXT DEFAULT NULL
) RETURNS void AS $$
BEGIN
    IF p_success THEN
        UPDATE public.email_outbox
        SET status = 'sent', sent_at = NOW()
        WHERE id = p_id;
    ELSE
        -- After max attempts the row stays 'pending' with attempts >= 5 and is
        -- skipped by claim; mark it failed explicitly for observability.
        UPDATE public.email_outbox
        SET status = CASE WHEN attempts >= 5 THEN 'failed' ELSE 'pending' END,
            last_error = p_error
        WHERE id = p_id;
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE ALL ON FUNCTION public.complete_email_delivery FROM anon, public;
