-- Migration: 20260818000001_shop_catalog_tables
-- Purpose: Add product_categories, product_items, product_skus, and order tables for shop catalog

-- 1. product_categories
CREATE TABLE IF NOT EXISTS public.product_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.product_categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "product_categories_public_select" ON public.product_categories
    FOR SELECT USING (true);

-- 2. product_items
CREATE TABLE IF NOT EXISTS public.product_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    currency TEXT NOT NULL DEFAULT 'EUR',
    stock INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'draft')),
    media JSONB NOT NULL DEFAULT '[]'::jsonb,
    category_id BIGINT REFERENCES public.product_categories(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_product_items_category_id ON public.product_items (category_id);
CREATE INDEX IF NOT EXISTS idx_product_items_status ON public.product_items (status);

ALTER TABLE public.product_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "product_items_public_select" ON public.product_items
    FOR SELECT USING (true);

-- 3. product_skus
CREATE TABLE IF NOT EXISTS public.product_skus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.product_items(id) ON DELETE CASCADE,
    label TEXT NOT NULL,
    options JSONB NOT NULL DEFAULT '{}'::jsonb,
    price DECIMAL(10, 2) NOT NULL,
    stock INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_product_skus_product_id ON public.product_skus (product_id);

ALTER TABLE public.product_skus ENABLE ROW LEVEL SECURITY;

CREATE POLICY "product_skus_public_select" ON public.product_skus
    FOR SELECT USING (true);

-- 4. order_headers
CREATE TABLE IF NOT EXISTS public.order_headers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency TEXT NOT NULL DEFAULT 'EUR',
    payment_provider TEXT NOT NULL DEFAULT 'manual',
    status TEXT NOT NULL DEFAULT 'pending_payment',
    subtotal_items DECIMAL(10, 2) NOT NULL,
    customer_notes TEXT,
    customer_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    recipient JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.order_headers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "order_headers_public_insert" ON public.order_headers
    FOR INSERT WITH CHECK (true);

CREATE POLICY "order_headers_select_own_or_admin" ON public.order_headers
    FOR SELECT USING (
        auth.uid() = customer_id
        OR EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = (SELECT auth.uid())
            AND profiles.role = 'admin'
        )
    );

-- 5. order_items
CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES public.order_headers(id) ON DELETE CASCADE,
    product_id TEXT NOT NULL,
    product_name TEXT NOT NULL,
    sku_id TEXT,
    sku_label TEXT,
    quantity INTEGER NOT NULL DEFAULT 1,
    unit_price DECIMAL(10, 2) NOT NULL,
    final_price DECIMAL(10, 2) NOT NULL,
    subtotal DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "order_items_public_insert" ON public.order_items
    FOR INSERT WITH CHECK (true);

CREATE POLICY "order_items_select" ON public.order_items
    FOR SELECT USING (true);
